import Link from 'next/link'
import {notFound} from 'next/navigation'
import {Shell,Mark} from '@/components/master/Shell'
import {readState} from '@/lib/master/store'
import {GATES,EXTRAS} from '@/lib/master/types'
import {loadClub} from '@/lib/clubs/resolver'
import {playable} from '@/lib/master/seed'
export const dynamic='force-dynamic'
export default async function Page({params}:{params:{slug:string}}){const c=(await readState()).clubs.find(c=>c.id===params.slug);if(!c)notFound();const open=playable(c);const core=await loadClub(c.id);return <Shell club={c}><main id="main"><section className="club-hero"><Mark club={c}/><div><p className="eyebrow">{c.city} / {c.country} / {c.status}</p><h1>{c.name}</h1><p className="spaced">One club. A whole world.</p></div></section><section className="section">{core&&c.status!=='paused'&&<div className="panel"><p className="eyebrow">TIMELINE / {core.data.readiness.state}</p><h2>Your history, in order.</h2><p className="spaced">{core.data.timeline.length} verified events. {core.data.readiness.state==='PARTIAL'?'A short round is available while more history is verified.':'The shared Timeline engine is ready to play.'}</p><Link href={`/clubs/${c.id}/timeline`} className="button">Play Timeline ↗</Link> <Link href={`/master/core?club=${c.id}`}>View evidence ↗</Link></div>}{open?<><div className="section-head"><h2>Your gates are open.</h2><Link href="/life" className="button">Enter LIFE ↗</Link></div><div className="gates">{GATES.filter(([n])=>c.gates.includes(n)).map(([n,name,url,desc])=><Link className="gate" href={url} key={n}><span>{n}</span><div><h3>{name}</h3><p>{desc}</p></div><b>↗</b></Link>)}</div><h2 className="spaced">Beyond the gates.</h2><div className="gates">{EXTRAS.map(([name,url,desc])=><Link className="gate" href={url} key={url}><div><h3>{name}</h3><p>{desc}</p></div><b>↗</b></Link>)}</div></>:<div className="panel"><p className="eyebrow">IN THE WORKSHOP</p><h2>A world built from its own history.</h2><p className="spaced">The remaining gates are being prepared. Research and game adapters must be verified before they open.</p><Link href="/master/admin" className="button">Open the evidence desk ↗</Link></div>}<details className="panel spaced"><summary>Readiness and outstanding work</summary><ul>{c.gaps.map(g=><li key={g}>{g}</li>)}</ul><p>{c.sources.length} sources / {c.findings.filter(f=>f.approved).length} approved findings</p></details></section></main></Shell>}
