#!/usr/bin/env python3 -I
"""Per-club archive index: what is in the club pack (approved / review), what the collector holds, and what is missing.
Reads club-packs/<club>/*.json and research-data/*. Writes docs/fanlife/research/archives/<club>.md + INDEX.md. No network."""
import json,os,sys,glob
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..','..'))
OUT=os.path.join(ROOT,'docs','fanlife','research','archives');os.makedirs(OUT,exist_ok=True)
SECTIONS=['players','matches','archive','trophies','kits','rivals','goals','mysteries','stadiums','places','culture','competitions','seasons','sources']
def load(p):
    try:return json.load(open(p,encoding='utf-8'))
    except Exception:return None
def count(pack):
    r={}
    for s in SECTIONS:
        v=pack.get(s) or []
        if not isinstance(v,list):continue
        if s=='sources':r[s]={'total':len(v),'available':sum(1 for x in v if isinstance(x,dict) and x.get('access')=='available')};continue
        ap=sum(1 for x in v if isinstance(x,dict) and x.get('status')=='approved')
        r[s]={'total':len(v),'approved':ap,'review':len(v)-ap}
    return r
clubs=sorted(set(os.listdir(os.path.join(ROOT,'club-packs')))|set(os.listdir(os.path.join(ROOT,'research-data','research-staging'))))
rows=[]
for c in clubs:
    packdir=os.path.join(ROOT,'club-packs',c);files=sorted(glob.glob(packdir+'/*.json'));tot={}
    for f in files:
        if os.path.basename(f) in('identity.json','ingest.json'):continue
        d=load(f)
        if not isinstance(d,dict):continue
        for s,v in count(d).items():
            t=tot.setdefault(s,{});
            for k,n in v.items():t[k]=t.get(k,0)+n
    rd=os.path.join(ROOT,'research-data');stg=os.path.join(rd,'research-staging',c);res=os.path.join(rd,'research',c)
    def n(p):
        x=load(p);return len(x) if isinstance(x,(list,dict)) else 0
    col={'docs':n(res+'/archive-docs.json'),'observations':n(res+'/archive-observations.json'),'candidate players':n(stg+'/archive-players.json'),'backlog':n(stg+'/backlog.json'),'staged sources':n(stg+'/sources.json')}
    L=[f'# {c} — archive index','',f'Pack files: {", ".join(os.path.basename(f) for f in files) or "none (collector only)"}','','| Section | Total | Approved | Review |','|---|---|---|---|']
    for s in SECTIONS:
        v=tot.get(s)
        if v:L.append(f'| {s} | {v.get("total",0)} | {v.get("approved","–") if s!="sources" else v.get("available",0)} | {v.get("review","–")} |')
    L+=['','Collector (research-data, never promoted without identity + approval):','']+[f'- {k}: {v}' for k,v in col.items()]
    gaps=[s for s in('players','matches','archive','kits','rivals','goals','mysteries') if not (tot.get(s) or {}).get('approved')]
    L+=['','Nothing approved yet in: '+(', '.join(gaps) if gaps else 'no core section is empty')]
    open(os.path.join(OUT,c+'.md'),'w',encoding='utf-8').write('\n'.join(L)+'\n')
    rows.append((c,tot,col))
I=['# Club archives — index','','Generated by scripts/club-research/build-archive-index.py. Approved = passed human approval with sources; review = staged, never reaches a game.','','| Club | Players | Matches | Archive | Kits | Collector docs | Candidate players |','|---|---|---|---|---|---|---|']
for c,t,col in rows:
    g=lambda s:f'{(t.get(s) or {}).get("approved",0)}/{(t.get(s) or {}).get("total",0)}'
    I.append(f'| [{c}]({c}.md) | {g("players")} | {g("matches")} | {g("archive")} | {g("kits")} | {col["docs"]} | {col["candidate players"]} |')
open(os.path.join(OUT,'INDEX.md'),'w',encoding='utf-8').write('\n'.join(I)+'\n')
print('\n'.join(I))
