import type { BlindCowBank } from './types'

/**
 * The duel questions, as SQL — the block between these two markers in
 * `supabase/migrations/20260924090000_worker_blind_cow.sql`, regenerated by
 * `npm run blind-cow:build`.
 *
 * A duel is graded by the DATABASE (spec §6.1, §10): both sides must get the same ten
 * clues in the same order and the answer must never cross to a browser, so the ten clues
 * and the answer id of every duel-eligible question live in `worker_blind_cow_question`,
 * a table nobody can read. On (question_id, version) a re-run rewrites NOTHING a duel may
 * stand on — only the `bank_version` tag moves forward, so a new duel is dealt only from
 * the questions of the newest bank, and a question the bank dropped stays for the old
 * duels that use it.
 */
export const SEED_BEGIN = '-- >>> blind-cow-seed'
export const SEED_END = '-- <<< blind-cow-seed'

function lit(text: string): string {
  return `'${text.replace(/'/g, "''")}'`
}

export function duelSeedSql(bank: BlindCowBank): string {
  const rows = bank.questions
    .filter((q) => q.eligibleModes.includes('duel'))
    .map((q) => {
      const clues = q.clueIds.map((id, i) => {
        const c = bank.clues[id]
        if (!c) throw new Error(`clue ${id} missing`)
        return { n: i + 1, labelHe: c.labelHe, valueHe: c.valueHe, type: c.type }
      })
      return `  (${lit(q.id)}, ${q.version}, ${lit(q.targetPlayerId)}, ${lit(JSON.stringify(clues))}::jsonb, ${bank.bankVersion})`
    })
  const lines = [
    SEED_BEGIN,
    `-- ${rows.length} שאלות דו-קרב, בנק גרסה ${bank.bankVersion}. נוצר ב-npm run blind-cow:build — לא עורכים ביד.`,
  ]
  if (rows.length) {
    lines.push(
      'insert into public.worker_blind_cow_question (question_id, version, target_player_id, clues, bank_version)',
      'values',
      rows.join(',\n'),
      // the content of a (question, version) never changes; only which bank it belongs to
      'on conflict (question_id, version) do update set bank_version = greatest(public.worker_blind_cow_question.bank_version, excluded.bank_version);',
    )
  }
  lines.push(SEED_END)
  return lines.join('\n')
}
