/**
 * The 24 V3 share compositions (FAN LIFE Share Studio V3, owner delivery 8.10.2026). Each is a print object for one
 * kind of share; the text here is the template's own fallback copy. The numbers are NOT gate numbers.
 * Data only — the renderer is `render.ts`, the club palette is `theme.ts`.
 */
export type ShareLayout='cover'|'team'|'score'|'programme'|'collection'|'exchange'|'memory'|'ballot'|'rumble'|'mystery'|'derby'|'archive'|'timeline'|'life'|'identity'|'journey'|'stand'|'wanted'|'gaps'|'daily'|'album'
export type ShareArt='archive-objects'|'away-supporters'|'father-child'|'footballer'|'scarf-fan'|'shirt-exchange'|'terrace-crowd'|'vintage-shirt'
export type ShareTemplate={id:string;name:string;surface:string;kind:string;gate:number|null;headline:string;context:string;main:string;label:string;detail:string;cta:string;rows:string[];route:string;layout:ShareLayout;art:ShareArt;rowLimit:number}
export const SHARE_TEMPLATES:readonly ShareTemplate[]=[
  {"id":"01-club-cover","name":"Club magazine cover","surface":"hub","kind":"cover","gate":null,"headline":"YOUR CLUB.\nYOUR LIFE.","context":"The stories. The shirts. The Saturdays.","main":"PLAY YOUR PART","label":"A FOOTBALL WORLD TO EXPLORE","detail":"History lives in the people who remember it.","cta":"Explore your club","rows":["PLAY","COLLECT","REMEMBER"],"route":"club","layout":"cover","art":"footballer","rowLimit":3},
  {"id":"02-all-time-xi","name":"My all-time XI","surface":"xi","kind":"xi","gate":1,"headline":"THE ONES\nI’D PICK.","context":"An all-time XI. One fan’s opinion.","main":"4-3-3","label":"MY TEAM SHEET","detail":"Captain: PLAYER 08","cta":"Pick your XI. Let’s compare.","rows":["PLAYER 01","PLAYER 02","PLAYER 03","PLAYER 04","PLAYER 05","PLAYER 06","PLAYER 07","PLAYER 08","PLAYER 09","PLAYER 10","PLAYER 11"],"route":"xi","layout":"team","art":"footballer","rowLimit":11},
  {"id":"03-trivia-report","name":"Trivia match report","surface":"trivia","kind":"score","gate":2,"headline":"THINK YOU\nKNOW YOUR CLUB?","context":"A quiz for the ones who were there.","main":"9/12","label":"MY TRIVIA RESULT","detail":"Best combo: 4 · Score: 840","cta":"Same questions. Your turn.","rows":["✓","✓","×","✓","✓","✓","×","✓","✓","×","✓","✓"],"route":"trivia","layout":"score","art":"scarf-fan","rowLimit":20},
  {"id":"04-lineup-programme","name":"Historical lineup programme","surface":"lineup","kind":"programme","gate":3,"headline":"THAT TEAM.\nTHAT AFTERNOON.","context":"A historic match · lineup challenge","main":"8/11","label":"STARTERS REMEMBERED","detail":"Match title and date come from the archive.","cta":"How many can you name?","rows":["MATCH PROGRAMME","SAMPLE MATCH","SAMPLE DATE"],"route":"lineup","layout":"programme","art":"footballer","rowLimit":3},
  {"id":"05-kit-memory","name":"Kit memory collector card","surface":"kit","kind":"kit","gate":4,"headline":"I REMEMBER\nTHE SHIRT.","context":"Kit Builder · my result","main":"3/3","label":"DETAILS RECALLED","detail":"Season. Maker. Design.","cta":"Can you remember the kit?","rows":["SEASON","MAKER","DESIGN"],"route":"kit-builder","layout":"score","art":"scarf-fan","rowLimit":3},
  {"id":"06-my-closet","name":"My shirt collection","surface":"wardrobe","kind":"closet","gate":5,"headline":"EVERY SHIRT.\nHAS A STORY.","context":"From my collection to yours.","main":"24","label":"SHIRTS IN MY COLLECTION","detail":"My favourite stays with me.","cta":"Show your colours.","rows":["1990s","2000s","2010s"],"route":"closet","layout":"collection","art":"shirt-exchange","rowLimit":3},
  {"id":"07-memory-contact","name":"Memory contact sheet","surface":"memory","kind":"contact","gate":6,"headline":"SOME THINGS\nSTICK WITH YOU.","context":"Memory · my completed board","main":"18","label":"TURNS · 6 PAIRS","detail":"A memory game, not an answer sheet.","cta":"Same board. Fewer turns?","rows":["01","02","03","04","05","06"],"route":"memory","layout":"memory","art":"archive-objects","rowLimit":6},
  {"id":"08-terrace-vote","name":"Terrace ballot","surface":"terrace","kind":"ballot","gate":7,"headline":"FOOTBALL.\nEVERYONE’S AN EXPERT.","context":"Terrace Vote · one fan’s opinion","main":"MY PICK","label":"THE TERRACE HAS OPINIONS","detail":"Who would you build your club around?","cta":"Agree? Cast your own vote.","rows":["SAMPLE PLAYER","YOUR PICK IS YOURS"],"route":"polls","layout":"ballot","art":"terrace-crowd","rowLimit":2},
  {"id":"09-goal-freeze","name":"Goal reconstruction report","surface":"goal","kind":"freeze","gate":8,"headline":"A MOMENT.\nREBUILT.","context":"Goal Reconstruction · my result","main":"84/100","label":"RECONSTRUCTION POINTS","detail":"The player. The action. The place.","cta":"Do you remember it better?","rows":["WHO","WHAT","WHERE"],"route":"goal","layout":"score","art":"footballer","rowLimit":3},
  {"id":"10-rumble-five","name":"Royal Rumble five","surface":"rumble","kind":"rumble","gate":9,"headline":"FIVE NAMES.\nONE BIG ARGUMENT.","context":"Royal Rumble · my five","main":"3–2","label":"SIMULATED MATCH RESULT","detail":"Budget used: 15/15","cta":"Build your five. Play the draft.","rows":["GK · PLAYER 01","DF · PLAYER 02","MF · PLAYER 03","FW · PLAYER 04","FW · PLAYER 05"],"route":"royal-rumble","layout":"rumble","art":"footballer","rowLimit":5},
  {"id":"11-blind-cow","name":"Blind Cow clue card","surface":"blindcow","kind":"clue","gate":10,"headline":"NOT A NAME.\nA FEW GOOD CLUES.","context":"Blind Cow · identity challenge","main":"2","label":"CLUES USED","detail":"Weighted time: 34.2s · Wrong guesses: 0","cta":"How soon will you know?","rows":["CLUE 01","CLUE 02","IDENTITY HIDDEN"],"route":"blind-cow","layout":"mystery","art":"archive-objects","rowLimit":3},
  {"id":"12-derby-file","name":"Derby archive poster","surface":"hate","kind":"derby","gate":11,"headline":"SOME MATCHES.\nNEVER LEAVE YOU.","context":"The derby · from the club archive","main":"THE DERBY","label":"A HISTORY BETWEEN TWO CLUBS","detail":"Remember the matches. Bring your version.","cta":"Open the derby archive.","rows":["YOUR CLUB","YOUR RIVAL","RECORDED MEETINGS"],"route":"derby","layout":"derby","art":"terrace-crowd","rowLimit":3},
  {"id":"13-archive-clipping","name":"Living archive clipping","surface":"archive","kind":"clipping","gate":12,"headline":"YOU HAD TO\nBE THERE.","context":"A story worth passing on.","main":"THE LIVING ARCHIVE","label":"A RECORD FROM MY CLUB","detail":"A short sourced excerpt goes here. Open the full record for context.","cta":"Open the archive.","rows":["RECORD TITLE","SOURCE CREDIT"],"route":"archive","layout":"archive","art":"terrace-crowd","rowLimit":2},
  {"id":"14-timeline-strip","name":"Timeline paper strip","surface":"timeline","kind":"timeline","gate":13,"headline":"HISTORY.\nIN THE RIGHT ORDER.","context":"Timeline · my result","main":"8/10","label":"EVENTS PLACED CORRECTLY","detail":"One timeline. Years of memories.","cta":"Same timeline. Your move.","rows":["?","?","?","?","?"],"route":"timeline","layout":"timeline","art":"archive-objects","rowLimit":12},
  {"id":"15-life-ticket","name":"LIFE chapter ticket","surface":"life","kind":"ticket","gate":null,"headline":"IT STARTED\nWITH A SATURDAY.","context":"LIFE · a chapter I completed","main":"FIRST MATCH","label":"ONE CHAPTER OF MY FOOTBALL LIFE","detail":"I kept the ticket. I remember the feeling.","cta":"Where does your story begin?","rows":["CHAPTER COMPLETE","SAMPLE CHAPTER","KEEPSAKE: MY FIRST TICKET"],"route":"life","layout":"life","art":"father-child","rowLimit":3},
  {"id":"16-supporter-passport","name":"Supporter identity card","surface":"member","kind":"passport","gate":null,"headline":"THE CLUB.\nTHE PERSON.","context":"A supporter’s identity · shared by choice","main":"SUPPORTER","label":"FAN LIFE · PERSONAL EDITION","detail":"The people. The place. The ritual.","cta":"What does your football look like?","rows":["PUBLIC ALIAS","MY CLUB","MY RITUAL"],"route":"member","layout":"identity","art":"scarf-fan","rowLimit":3},
  {"id":"17-away-days","name":"Away Days travel passport","surface":"away","kind":"away","gate":null,"headline":"SOME MILES.\nSAME COLOURS.","context":"Away Days · my journey","main":"7","label":"GROUNDS I’VE VISITED","detail":"4 countries · 11 matches","cta":"Where have your colours taken you?","rows":["GROUND 01","GROUND 02","GROUND 03"],"route":"away","layout":"journey","art":"away-supporters","rowLimit":3},
  {"id":"18-stand-invitation","name":"Stand invitation","surface":"stand","kind":"stand","gate":null,"headline":"THERE’S ROOM\nIN OUR STAND.","context":"A private stand · join by invitation","main":"THE SATURDAY CLUB","label":"OUR GROUP’S NAME","detail":"One place for our football arguments.","cta":"Take your place in our stand.","rows":["PLAY TOGETHER","COMPARE RESULTS","PASS IT ON"],"route":"stand","layout":"stand","art":"terrace-crowd","rowLimit":3},
  {"id":"19-shirt-wanted","name":"Wanted shirt notice","surface":"wanted","kind":"wanted","gate":5,"headline":"ONE SHIRT.\nSTILL LOOKING.","context":"Shirt collection · a collector’s request","main":"YOUR SEASON","label":"HOME SHIRT · SIZE M","detail":"If it’s in your collection, let’s talk.","cta":"Know someone who has it?","rows":["SEASON","SIZE","CONDITION"],"route":"wanted","layout":"wanted","art":"vintage-shirt","rowLimit":3},
  {"id":"20-collection-gaps","name":"Missing seasons checklist","surface":"gaps","kind":"gaps","gate":5,"headline":"THE ONES\nI’M MISSING.","context":"My shirt collection · missing seasons","main":"3","label":"SEASONS I’M STILL LOOKING FOR","detail":"Pass this to the collector you know.","cta":"Got one of these?","rows":["SEASON 01","SEASON 02","SEASON 03"],"route":"gaps","layout":"gaps","art":"vintage-shirt","rowLimit":5},
  {"id":"21-trade-completed","name":"Completed shirt exchange","surface":"match","kind":"trade","gate":5,"headline":"NEW HANDS.\nSAME LOVE.","context":"Shirt exchange · connection completed","main":"MATCH MADE","label":"TWO COLLECTORS. TWO STORIES.","detail":"Shirts change hands. The stories stay.","cta":"Find your next shirt connection.","rows":["MY SHIRT","THEIR SHIRT"],"route":"trade","layout":"exchange","art":"shirt-exchange","rowLimit":2},
  {"id":"22-on-this-day","name":"On this day archive notice","surface":"archive","kind":"date","gate":12,"headline":"THIS DAY.\nSTILL WITH US.","context":"On this day · from the archive","main":"24 MAY","label":"THE YEAR FROM THE RECORD","detail":"The exact date and historical caption go here.","cta":"What do you remember?","rows":["EVENT TITLE","SOURCE CREDIT"],"route":"onthisday","layout":"archive","art":"archive-objects","rowLimit":2},
  {"id":"23-daily-challenge","name":"Daily challenge invitation","surface":"daily","kind":"daily","gate":null,"headline":"YOU. ME.\nTHE SAME QUESTIONS.","context":"An open challenge · no answers here","main":"YOUR TURN","label":"A FRESH REASON TO COME BACK","detail":"Send it to the friend who always knows.","cta":"Play the same challenge.","rows":["PLAY","COMPARE","PASS IT ON"],"route":"daily","layout":"daily","art":"scarf-fan","rowLimit":3},
  {"id":"24-life-album","name":"LIFE keepsake album","surface":"life","kind":"album","gate":null,"headline":"THE THINGS\nWE KEEP.","context":"LIFE · my completed album page","main":"MY KEEPSAKES","label":"THE OBJECTS THAT CAME WITH ME","detail":"Some things belong in a box. Some things deserve a story.","cta":"What would you have kept?","rows":["FIRST TICKET","OLD SCARF","MATCH PROGRAMME","A SHIRT"],"route":"life","layout":"album","art":"archive-objects","rowLimit":4}
]
export const templateById=(id:string)=>SHARE_TEMPLATES.find(t=>t.id===id)
