import {NextRequest,NextResponse} from 'next/server'
import {randomUUID} from 'node:crypto'
import {audit,mutate,readState} from '@/lib/master/store'
import {sameOrigin,requireOpenEvaluation,cronAuthorized,text,slug,color} from '@/lib/master/request'
import {runResearch} from '@/lib/master/research'
import {checkUpstream} from '@/lib/master/upstream'
import type {Club} from '@/lib/master/types'
export const dynamic='force-dynamic'
export const maxDuration=60
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}})
export async function GET(r:NextRequest,{params}:{params:{action:string[]}}){try{requireOpenEvaluation();const a=params.action.join('/');if(a==='cron'){if(!cronAuthorized(r))return json({error:'Invalid scheduler authorization'},401);return json(await runResearch())}if(a==='state')return json(await readState());if(a==='export')return new NextResponse(JSON.stringify(await readState(),null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="fan-life-control.json"','Cache-Control':'no-store'}});return json({error:'Not found'},404)}catch(e){return json({error:e instanceof Error?e.message:'Operation failed'},400)}}
export async function POST(r:NextRequest,{params}:{params:{action:string[]}}){try{requireOpenEvaluation();sameOrigin(r);const a=params.action.join('/');if(a==='upstream/check')return json(await checkUpstream());if(a==='research/run')return json(await runResearch());const raw=await r.text();if(raw.length>250000)throw new Error('Request too large.');const b=JSON.parse(raw);
if(a==='clubs/create')return json(await mutate(s=>{const id=slug(b.id);if(s.clubs.some(c=>c.id===id))throw new Error('Club already exists.');if(s.clubs.length>=100)throw new Error('Registry limit reached.');const c:Club={id,name:text(b.name,'Name'),city:text(b.city,'City'),country:text(b.country,'Country'),initials:text(b.initials,'Initials',4),primary:color(b.primary),secondary:color(b.secondary),status:'research',version:1,gates:[],sources:[],findings:[],gaps:['Research and native content adapter required.']};s.clubs.push(c);audit(s,'club.created',id);return c}),201);
if(a==='clubs/update')return json(await mutate(s=>{const c=s.clubs.find(c=>c.id===b.id);if(!c||c.version!==b.version)throw new Error('Club changed. Reload before saving.');if(!['research','review','live','paused'].includes(b.status))throw new Error('Invalid status.');if(b.status==='live'&&c.id!=='hapoel-tel-aviv')throw new Error('A tested native adapter is required before activation.');if(!Array.isArray(b.gates)||b.gates.some((n:unknown)=>typeof n!=='number'||!Number.isInteger(n)||n<1||n>13))throw new Error('Invalid gate selection.');Object.assign(c,{name:text(b.name,'Name'),primary:color(b.primary),secondary:color(b.secondary),status:b.status,gates:[...new Set(b.gates)],version:c.version+1});audit(s,'club.updated',c.id);return c}));
if(a==='research/create')return json(await mutate(s=>{const id=slug(b.clubId);if(!s.clubs.some(c=>c.id===id))throw new Error('Club not found.');if(s.jobs.some(j=>j.clubId===id&&['queued','running'].includes(j.status)))throw new Error('Research already queued.');const job={id:randomUUID(),clubId:id,query:text(b.query,'Query'),title:b.title?text(b.title,'Article title'):undefined,status:'queued' as const,attempts:0,createdAt:new Date().toISOString()};s.jobs.push(job);audit(s,'research.queued',id);return job}),201);
if(a==='research/retry')return json(await mutate(s=>{const j=s.jobs.find(j=>j.id===b.id);if(!j||j.status!=='failed')throw new Error('Only failed jobs can be retried.');j.status='queued';j.attempts=0;delete j.error;audit(s,'research.retried',j.clubId);return j}));
if(a==='evidence/approve')return json(await mutate(s=>{const c=s.clubs.find(c=>c.id===b.clubId);if(!c||c.version!==b.version)throw new Error('Club changed. Reload first.');if(b.kind==='source'){const src=c.sources.find(x=>x.id===b.id);if(!src)throw new Error('Source not found.');src.reviewed=true}else{const f=c.findings[Number(b.index)];if(!f||!f.sources.length||f.sources.some(id=>!c.sources.some(x=>x.id===id&&x.reviewed)))throw new Error('Review cited sources first.');f.approved=true}c.version++;audit(s,'evidence.approved',c.id);return c}));
return json({error:'Unknown operation'},404)}catch(e){return json({error:e instanceof Error?e.message:'Operation failed'},400)}}
