import {chapter, scene, s, o} from './write'
import {flag, is, bond} from './types'

export const ADULTHOOD = [
chapter('c5a-last-bus',18,2,['The last bus','האוטובוס האחרון'],['The station board goes dark. The scarves are still on. Nobody knows whose idea it was to stop for food.','לוח התחנה כבה. הצעיפים עדיין על הצוואר. אף אחד לא זוכר מי הציע לעצור לאכול.'],'last-bus-note',['A folded phone number','מספר טלפון מקופל'],['A ride can last longer than the journey.','טרמפ יכול להישאר איתך הרבה אחרי הנסיעה.'],[
scene('S19','bus-station','friend',['No bus','אין אוטובוס'],[s('friend','Tell me that says delayed, not tomorrow.','תגיד לי שכתוב שם עיכוב ולא מחר.'),s(null,'Your friend laughs, then checks the same empty pocket again.','החבר צוחק, ואז בודק שוב את אותו כיס ריק.')],['Make the call','לבצע את השיחה'],[s(null,'The public phone swallows the coin. You wait for somebody to answer.','הטלפון הציבורי בולע את המטבע. אתה מחכה שמישהו יענה.')],[
o('dad','Call Dad and tell the whole story','להתקשר לאבא ולספר הכול','dad','I will come. Stand where there is light. We can discuss the sandwich later.','אני בא. תעמדו איפה שיש אור. על הסנדוויץ׳ נדבר אחר כך.',[flag('life:ride:helper','dad'),flag('life:home:trust','open'),bond('dad',3)]),
o('friend','Accept the friend’s lift; repay the petrol','לקבל טרמפ מהחבר ולהחזיר על הדלק','friend','My brother can collect us. You owe me petrol, not your life.','אחי יכול לאסוף. אתה חייב לי דלק, לא את החיים שלך.',[flag('life:ride:helper','friend'),flag('life:promise:ride','open')]),
o('rival','Call the rival you actually know','להתקשר לאוהד היריבה שכבר הכרנו','rival','You want a lift in this scarf? All right. The scarf goes in the boot. Joking.','טרמפ עם הצעיף הזה? טוב. הצעיף בתא המטען. סתם, תעלה.',[flag('life:ride:helper','rival'),flag('life:promise:ride','open'),bond('rival',4)],is('life:rival:link','open')),
o('wait','Wait together for the morning service','לחכות יחד לקו הראשון','friend','Then we share the bench. You get the half without the puddle.','אז מתחלקים בספסל. אתה מקבל את החצי בלי השלולית.',[flag('life:ride:helper','morning')])]),
scene('S20','bus-stop','friend',['The meeting point','נקודת המפגש'],[s('friend','Someone must move the bags. Someone must stay by the sign.','מישהו צריך לקחת את התיקים. מישהו צריך להישאר ליד השלט.')],['Move the bags and meet the group','להעביר את התיקים ולפגוש את כולם'],[s(null,'You check the sign, the bags and the people. This is a journey, not an escape.','אתה בודק את השלט, התיקים והאנשים. זו נסיעה, לא בריחה.')],[
o('carry','Carry the extra bag','לקחת גם את התיק הנוסף','friend','You brought half the ground in that bag. Thank you.','הבאת חצי יציע בתיק הזה. תודה.',[flag('life:ride:care','carried'),bond('friend',2)]),
o('check','Count people before leaving','לספור אנשים לפני שיוצאים',null,'Everyone answers. One answer comes from inside a scarf.','כולם עונים. תשובה אחת מגיעה מתוך צעיף.',[flag('life:ride:care','counted')]),
o('shelter','Move the waiting group under cover','להעביר את המחכים למחסה','friend','First useful tactical change of the evening.','החילוף הטקטי המועיל הראשון של הערב.',[flag('life:ride:care','sheltered')])],'carry'),
scene('S21','kitchen','dad',['The next morning','בבוקר שאחרי'],[s('dad','You look like a man who spent the night arguing with a timetable.','אתה נראה כמו אדם שרב כל הלילה עם לוח זמנים.')],['Leave a note about the night','להשאיר פתק על הלילה'],[s(null,'The kettle clicks. You put the note beside the sugar, where somebody will see it.','הקומקום נוקש. אתה מניח פתק ליד הסוכר, במקום שבאמת יראו.')],[
o('repay','Repay the petrol now with an errand','להחזיר את הדלק עכשיו בעזרה בסידור','friend','You carried the boxes all morning. We are even. I still get to tell the story.','סחבת ארגזים כל הבוקר. אנחנו בסדר. עדיין מותר לי לספר את הסיפור.',[flag('life:promise:ride','kept')],{flag:'life:promise:ride'}),
o('later','Write a real repayment promise','לכתוב הבטחה להחזיר בהמשך','friend','Put it on paper. Your memory improves dramatically near a ticket office.','תרשום. ליד קופת כרטיסים הזיכרון שלך משתפר פלאים.',[flag('life:promise:ride','open')],{flag:'life:promise:ride'}),
o('tell','Tell the family what happened','לספר בבית מה באמת קרה','dad','A wrong turn is repairable. A missing person is harder. Next time, call earlier.','טעות בדרך אפשר לתקן. בן אדם שנעלם יותר קשה. בפעם הבאה תתקשר מוקדם.',[flag('life:ride:account','told'),bond('dad',2)])])]),

chapter('c6-work',21,2,['The shift','המשמרת'],['The shift board and the match notice cover the same Saturday. Your boss has already circled your name.','לוח המשמרות והמודעה על המשחק מכסים את אותה שבת. הבוס כבר הקיף את השם שלך.'],'shift-slip',['A shift slip','פתק משמרת'],['An agreement has a second person in it.','בהסכם יש עוד אדם.'],[
scene('S22','workshop','boss',['Two Saturdays','שתי שבתות'],[s('boss','You may swap, but do not write another person’s name for them.','אפשר להחליף. אל תכתוב שם של מישהו אחר במקומו.'),s('mate','Ask me. I am standing right here.','תשאל אותי. אני עומד ממש פה.')],['Write the agreed shift','לרשום את המשמרת שסוכמה'],[s(null,'You take the pencil and check the board with the people affected.','אתה לוקח עיפרון ובודק את הלוח עם האנשים שהסיכום נוגע להם.')],[
o('swap','Agree on a swap and a return shift','לסכם החלפה ומשמרת החזרה','mate','I cover this one. You cover mine next week. Agreed?','אני מכסה הפעם. אתה בשבוע הבא. סגור?',[flag('life:promise:shift','open'),flag('life:work:route','swap')]),
o('stay','Keep the shift and follow later','להישאר במשמרת ולהתעדכן אחר כך','boss','Work first. Then turn the radio up. Not next to the saw.','קודם עבודה. אחר כך תגביר רדיו. לא ליד המסור.',[flag('life:work:route','stay')]),
o('half','Agree a shorter shift before the match','לסכם משמרת קצרה לפני המשחק','boss','Finish these shelves. Then go. A half-finished shelf is not a shorter shift.','תסיים את המדפים האלה ואז צא. מדף חצי גמור זו לא משמרת קצרה.',[flag('life:work:route','half')])]),
scene('S23','workshop','mate',['The other half of the agreement','החצי השני של ההסכם'],[s(null,'Another workday arrives. There is no match notice to make this one exciting.','מגיע יום עבודה נוסף. אין מודעת משחק שהופכת אותו למרגש.')],['Finish the work or report the absence','לסיים את העבודה או לדווח על ההיעדרות'],[s(null,'You go to the board again. The agreement now needs an action.','אתה חוזר ללוח. עכשיו ההסכם צריך מעשה.')],[
o('work','Work the agreed hours','לעבוד את השעות שסוכמו','mate','There you are. Apron on. The radio is already tuned.','הנה אתה. שים סינר. הרדיו כבר מכוון.',[flag('life:promise:shift','kept'),{e:'coins',by:24},bond('mate',3)]),
o('renegotiate','Ask for a new date before the shift','לבקש מועד חדש לפני המשמרת','mate','I can do Tuesday. Write it down and call me if it changes.','שלישי אפשר. תרשום ותתקשר אם זה משתנה.',[flag('life:promise:shift','open'),{e:'coins',by:12}]),
o('miss','Fail to arrive and face the call','לא להגיע ולהתמודד עם השיחה','mate','I waited. Next time your name on the board needs to mean something.','חיכיתי. בפעם הבאה השם שלך על הלוח צריך להיות שווה משהו.',[flag('life:promise:shift','broken'),bond('mate',-5)])],'count'),
scene('S24','street','friend',['After the shift','אחרי המשמרת'],[s('friend','How was it? The work, I mean. You always answer with football.','איך היה? בעבודה, התכוונתי. אתה תמיד עונה עם כדורגל.')],['Choose where the evening continues','לבחור איפה ממשיכים את הערב'],[s(null,'You put the slip in your pocket and make room for the evening.','אתה מקפל את הפתק בכיס ומפנה מקום לערב.')],[
o('ground','Meet near the ground','להיפגש ליד המגרש','friend','I will bring food. You bring the story that is not about the referee.','אני אביא אוכל. אתה תביא סיפור שלא קשור לשופט.',[flag('life:work:evening','ground')]),
o('home','Invite the friend home','להזמין את החבר הביתה','friend','A chair with a back. We have finally made it.','כיסא עם משענת. סוף סוף הצלחנו בחיים.',[flag('life:work:evening','home')]),
o('quiet','Take an evening to yourself','לקחת ערב לעצמך',null,'You walk slowly. Football will still exist tomorrow.','אתה הולך לאט. הכדורגל יהיה שם גם מחר.',[flag('life:work:evening','quiet')])])]),

chapter('c6b-our-saturday',24,2,['Our Saturday','השבת שלנו'],['Someone close wants a place in your calendar, not a seat left over after everything else.','מישהו קרוב רוצה מקום בלוח שלך, לא כיסא שנשאר אחרי כל השאר.'],'shared-calendar',['A page from a calendar','דף מלוח השנה'],['Two people wrote on this page.','שני אנשים כתבו בדף הזה.'],[
scene('S25','room','friend',['An actual invitation','הזמנה אמיתית'],[s('friend','When you say see you Saturday, do you mean before the game, after it, or in a different lifetime?','כשאתה אומר נתראה בשבת, זה לפני המשחק, אחריו או בחיים אחרים?')],['Write a time together','לכתוב שעה יחד'],[s(null,'The calendar stays open. Nobody agrees on behalf of the other person.','הלוח נשאר פתוח. אף אחד לא מסכים בשם האדם השני.')],[
o('relationship','Talk about building a shared life','לשוחח על בניית חיים משותפים','friend','I want that too. Let us talk about what it would actually look like.','גם אני רוצה. בוא נדבר איך זה ייראה באמת.',[flag('life:household:kind','partner')]),
o('friendship','Protect a regular time for friendship','לקבוע זמן קבוע לחברות','friend','One evening that does not begin with you checking the score. Deal.','ערב אחד שלא מתחיל בזה שאתה בודק תוצאה. סגור.',[flag('life:household:kind','friend')]),
o('space','Be honest about needing your own space','להגיד בכנות שצריך מרחב אישי','friend','Fine. Then invite me when you have room, and mean it.','בסדר. אז תזמין כשיש לך מקום ותתכוון לזה.',[flag('life:household:kind','solo')])]),
scene('S26','kitchen','friend',['What we agree to','מה שסיכמנו'],[s('friend','A home is more than a fixture list. What do you want to make room for?','בית הוא יותר מלוח משחקים. למה אתה רוצה לפנות מקום?')],['Put the shared plan on paper','להעלות את התוכנית המשותפת על הנייר'],[s(null,'You write, stop, and check that the other person wants the same thing.','אתה כותב, עוצר ובודק שגם האדם השני רוצה את אותו הדבר.')],[
o('children','Agree, together, to consider parenthood later','להסכים יחד לשקול הורות בעתיד','friend','I want us to explore that together. A wish is not a child; we have years to decide.','אני רוצה שנבדוק את זה יחד. רצון הוא עדיין לא ילד; יש לנו שנים להחליט.',[flag('life:family:intent','parent')],is('life:household:kind','partner')),
o('nochildren','Choose a shared life without parenting','לבחור חיים משותפים בלי הורות','friend','Then this is our home too. It does not need to copy anybody else’s.','אז גם זה הבית שלנו. הוא לא צריך להעתיק בית של אף אחד.',[flag('life:family:intent','nochild')],is('life:household:kind','partner')),
o('people','Make room for people without a family plan','לפנות מקום לאנשים בלי תוכנית משפחתית','friend','A table, a spare chair, and an invitation that really happens. Start there.','שולחן, כיסא נוסף והזמנה שבאמת מתקיימת. נתחיל בזה.',[flag('life:family:intent','open')])]),
scene('S27','gate','friend',['The overtime that was not agreed','התוספת שלא סוכמה'],[s(null,'Your phone rings. You said you would be back by seven. A friend is suggesting one more stop.','הטלפון מצלצל. אמרת שתחזור בשבע. חבר מציע עוד עצירה אחת.')],['Act on the plan or change it honestly','לקיים את התוכנית או לשנות אותה בכנות'],[s(null,'You step away from the queue and make the call before deciding.','אתה יוצא מהתור ומתקשר לפני שאתה מחליט.')],[
o('leave','Go back at the agreed time','לחזור בזמן שסוכם','friend','You came. I saved the good chair, not the good score.','הגעת. שמרתי לך את הכיסא הטוב, לא את התוצאה הטובה.',[flag('life:promise:home','kept'),bond('friend',3)]),
o('ask','Agree a different evening with the other person','לסכם ערב אחר עם האדם השני','friend','Tomorrow works for me. This is a change we both made.','מחר מתאים לי. זה שינוי ששנינו עשינו.',[flag('life:promise:home','open')]),
o('late','Stay and arrive after everyone has left','להישאר ולהגיע אחרי שכולם הלכו','friend','The food is in the fridge. The evening is not.','האוכל במקרר. הערב כבר לא.',[flag('life:promise:home','broken'),bond('friend',-4)])])]),

chapter('c6c-world-opens',25,2,['The other scarf','הצעיף האחר'],['A visiting supporter asks a simple question. You discover how much of your city you have never had to explain.','אוהד אורח שואל שאלה פשוטה. אתה מגלה כמה מהעיר שלך מעולם לא היית צריך להסביר.'],'visitor-map',['A map with two handwritings','מפה בשני כתבי יד'],['No invented fixture or foreign trophy is written on it.','לא רשומים בה משחק מומצא או תואר אירופי שלא היה.'],[
scene('S28','street','seller',['Which way?','לאן הולכים?'],[s('seller','They asked me for the ground. I sent them to the bakery. In my defence, it is a very good bakery.','שאלו אותי איפה המגרש. שלחתי למאפייה. להגנתי, זו מאפייה מצוינת.')],['Mark an actual meeting place','לסמן נקודת מפגש ברורה'],[s(null,'You draw a route on the back of a receipt. There is room for a name and a meeting time.','אתה מצייר מסלול בגב קבלה. יש מקום לשם ולשעת מפגש.')],[
o('guide','Walk with the visitor','ללוות את האורח ברגל',null,'The visitor points at your scarf, then at theirs. Names become easier.','האורח מצביע על הצעיף שלך ואז על שלו. השמות כבר קלים יותר.',[flag('life:visitor:route','guide')]),
o('introduce','Introduce someone who can guide them','להכיר להם מישהו שיוכל ללוות','friend','I can help. Ask them if they want company first.','אני יכול לעזור. קודם תשאל אם הם רוצים חברה.',[flag('life:visitor:route','introduce')]),
o('map','Give clear directions and a contact number','לתת הוראות ברורות ומספר קשר',null,'You check that the directions make sense from their side of the paper.','אתה בודק שההוראות מובנות גם מהצד שלהם של הדף.',[flag('life:visitor:route','map')])]),
scene('S29','gate','steward',['The closed entrance','הכניסה הסגורה'],[s('steward','This entrance is closed today. Use the one marked on the board.','הכניסה הזו סגורה היום. תשתמשו בזו שמסומנת על הלוח.')],['Read the sign and correct the route','לקרוא את השלט ולתקן את הדרך'],[s(null,'You compare the sign with the receipt. The confident arrow was wrong.','אתה משווה את השלט לקבלה. החץ הבטוח היה שגוי.')],[
o('admit','Admit the mistake and walk round','להודות בטעות ולעשות את הסיבוב',null,'The visitor laughs with you. You are both following the sign now.','האורח צוחק איתך. עכשיו שניכם הולכים לפי השלט.',[flag('life:visitor:trust','open')]),
o('ask','Ask the steward to explain the accessible route','לבקש מהסדרן להסביר את המסלול הנגיש','steward','A little longer, fewer steps. Here is where you turn.','קצת יותר ארוך, פחות מדרגות. כאן פונים.',[flag('life:visitor:trust','care')]),
o('handoff','Hand over to the guide you introduced','להעביר את הליווי למי שהכרתם','friend','I have them. Your arrow now leads to a story, which is an improvement.','הם איתי. החץ שלך מוביל עכשיו לסיפור, שזה שיפור.',[flag('life:visitor:trust','shared')])]),
scene('S30','room','friend',['Keep in touch','נשמור על קשר'],[s('friend','You have a name and a city, not a free holiday. What happens next?','יש לך שם ועיר, לא חופשה חינם. מה הלאה?')],['Send the message you promised','לשלוח את ההודעה שהבטחת'],[s(null,'You write a short message and actually send it.','אתה כותב הודעה קצרה ובאמת שולח אותה.')],[
o('regular','Begin an occasional exchange','להתחיל קשר מדי פעם',null,'A reply arrives: their scarf is drying on a chair too.','מגיעה תשובה: גם הצעיף שלהם מתייבש על כיסא.',[flag('life:visitor:contact','regular')]),
o('visit','Say you may visit, without booking anything','לומר שאולי תבקר, בלי להזמין נסיעה',null,'You save the address. A possibility is a possibility, not a ticket.','אתה שומר כתובת. אפשרות היא אפשרות, לא כרטיס.',[flag('life:visitor:contact','possible')]),
o('thanks','Thank them and leave it as one good encounter','להודות ולהשאיר מפגש טוב אחד',null,'The map goes into the box. Not every good meeting needs a sequel.','המפה נכנסת לקופסה. לא כל מפגש טוב צריך המשך.',[flag('life:visitor:contact','closed')])])]),

chapter('c6a-empty',26,2,['The empty seat','הכיסא הריק'],['Your friend misses several Saturdays. The team is still playing. His life has become bigger than the terrace.','החבר מחמיץ כמה שבתות. הקבוצה עדיין משחקת. החיים שלו נהיו גדולים יותר מהיציע.'],'empty-seat-note',['An invitation without a deadline','הזמנה בלי תאריך תפוגה'],['Space is not the same thing as absence.','מרחב הוא לא אותו דבר כמו היעדרות.'],[
scene('S31','terrace','friend',['No attendance register','בלי פנקס נוכחות'],[s('friend','I have things at home. I do not need a trial every time I miss a game.','יש לי דברים בבית. אני לא צריך משפט בכל פעם שאני מפסיד משחק.')],['Send an invitation with room to refuse','לשלוח הזמנה שאפשר גם לסרב לה'],[s(null,'You take the accusation out of the message before sending it.','אתה מוציא את ההאשמה מההודעה לפני שאתה שולח.')],[
o('seat','Keep a place when he wants to return','לשמור מקום כשירצה לחזור','friend','That helps. Just do not sell it as a rescue operation.','זה עוזר. רק אל תמכור את זה כמבצע חילוץ.',[flag('life:friend:distance','seat')]),
o('home','Offer a visit away from football','להציע ביקור שלא קשור לכדורגל','friend','Thursday. Tea. No commentary voice in my kitchen.','חמישי. תה. בלי קול של שדרן במטבח שלי.',[flag('life:friend:distance','visit')]),
o('space','Give space and a clear way to reconnect','לתת מרחב ודרך ברורה לחזור לקשר','friend','I will call. Thank you for not making the silence louder.','אני אתקשר. תודה שלא הפכת את השקט לרועש יותר.',[flag('life:friend:distance','space')])]),
scene('S32','kitchen','friend',['Do the small thing','לעשות את הדבר הקטן'],[s(null,'The agreed day arrives. There is no crowd to applaud showing up.','מגיע היום שסוכם. אין קהל שימחא כפיים על זה שהגעת.')],['Carry out the invitation','לבצע את ההזמנה'],[s(null,'You put the kettle on, check the message, and follow the terms of the invitation.','אתה מפעיל קומקום, בודק את ההודעה ופועל לפי תנאי ההזמנה.')],[
o('listen','Listen without fixing his life','להקשיב בלי לתקן לו את החיים','friend','I did not need an answer. I needed you to stay until I finished.','לא הייתי צריך תשובה. הייתי צריך שתישאר עד שאסיים.',[flag('life:friend:care','listened'),bond('friend',4)]),
o('practical','Offer one task and ask before doing it','להציע עזרה אחת ולשאול לפני שעושים','friend','You can bring the bag tomorrow. That would actually help.','את התיק תוכל להביא מחר. זה באמת יעזור.',[flag('life:friend:care','practical')]),
o('light','Share something funny and keep it brief','לשתף משהו מצחיק ולשמור על ביקור קצר','friend','Ten minutes of normal nonsense. I missed that.','עשר דקות של שטויות רגילות. לזה התגעגעתי.',[flag('life:friend:care','light')])]),
scene('S33','bedroom','dad',['The seat is not a verdict','הכיסא הוא לא פסק דין'],[s('dad','People change their Saturdays. That does not erase the Saturdays you had.','אנשים משנים את השבתות שלהם. זה לא מוחק את השבתות שהיו לכם.')],['Save a memory without deciding for the friend','לשמור זיכרון בלי להחליט עבור החבר'],[s(null,'You fold the note. There is no return date on it.','אתה מקפל את הפתק. אין עליו תאריך חזרה.')],[
o('open','Leave the invitation open','להשאיר הזמנה פתוחה',null,'There is a place, and no attendance register.','יש מקום, ואין פנקס נוכחות.',[flag('life:friend:return','open')]),
o('different','Build a different kind of friendship','לבנות חברות מסוג אחר',null,'Next time you meet, nobody asks about the table.','בפגישה הבאה אף אחד לא שואל על הטבלה.',[flag('life:friend:return','different')]),
o('accept','Accept that contact may become occasional','להסכים שהקשר יהיה מדי פעם',null,'The good years remain good years.','השנים הטובות נשארות שנים טובות.',[flag('life:friend:return','occasional')])])]),

chapter('c7-far',30,2,['Distance','מרחק'],['A suitcase stands by the door. It may be yours, or the friend’s. The distance needs a plan either way.','מזוודה עומדת ליד הדלת. היא יכולה להיות שלך או של החבר. המרחק צריך תוכנית בכל מקרה.'],'distance-note',['Two times on one clock','שתי שעות על שעון אחד'],['Staying can change a life too.','גם להישאר יכול לשנות חיים.'],[
scene('S34','room','friend',['Whose suitcase?','של מי המזוודה?'],[s('friend','We have talked about moving for months. Decide what we are actually saying goodbye to.','דיברנו על מעבר חודשים. בוא נחליט ממה אנחנו באמת נפרדים.')],['Label the suitcase or close it','לסמן את המזוודה או לסגור אותה'],[s(null,'You put a name on the luggage tag. A possible move becomes a chosen route.','אתה כותב שם על תג המזוודה. מעבר אפשרי הופך למסלול שנבחר.')],[
o('abroad','Take the agreed opportunity abroad','לקחת את ההזדמנות שסוכמה בחו״ל','friend','Then we set a time to call. Not whenever the match ends.','אז קובעים זמן לשיחה. לא מתי שהמשחק ייגמר.',[flag('life:home:place','abroad')]),
o('stay','Stay while the friend moves','להישאר כשהחבר עובר','friend','You will know the old streets. I will tell you about the new ones.','אתה תכיר את הרחובות הישנים. אני אספר על החדשים.',[flag('life:home:place','home')]),
o('defer','Defer the move and choose life here','לדחות את המעבר ולבחור בחיים כאן','friend','Then unpack. A closed suitcase is not a life plan.','אז תפרוק. מזוודה סגורה היא לא תוכנית לחיים.',[flag('life:home:place','home')])]),
scene('S35','flat-abroad','friend',['The first real call','השיחה האמיתית הראשונה'],[s(null,'The room on the screen is unfamiliar. Somebody is there; somebody is calling from home.','החדר במסך לא מוכר. מישהו שם; מישהו מתקשר מהבית.'),s('friend','Five minutes without pretending everything is wonderful?','חמש דקות בלי להעמיד פנים שהכול נפלא?')],['Make the scheduled call','לקיים את השיחה שנקבעה'],[s(null,'You set the clock aside and let the other person finish.','אתה מניח את השעון בצד ונותן לאדם השני לסיים.')],[
o('honest','Say what is actually difficult','לספר מה באמת קשה','friend','Good. Now we can talk to a person instead of a postcard.','טוב. עכשיו אפשר לדבר עם אדם ולא עם גלויה.',[flag('life:distance:talk','honest'),bond('friend',3)]),
o('routine','Make a small shared routine','לקבוע שגרה קטנה משותפת','friend','One meal, one call. Football can join us sometimes.','ארוחה אחת, שיחה אחת. הכדורגל יכול להצטרף לפעמים.',[flag('life:distance:talk','routine')]),
o('short','Keep this call short and book the next one','לקצר הפעם ולקבוע את השיחה הבאה','friend','Next Sunday, then. I will put it where I can see it.','אז ביום ראשון הבא. אשים את זה במקום שאוכל לראות.',[flag('life:distance:talk','short')])]),
scene('S36','kitchen','dad',['A place at the table','מקום ליד השולחן'],[s('dad','You can be far away and still call. You can live next door and forget.','אפשר להיות רחוק ועדיין להתקשר. אפשר לגור ליד ולשכוח.')],['Make the family call or visit','לקיים שיחה או ביקור משפחתי'],[s(null,'You make contact before putting the phone away. Distance is not decided by kilometres alone.','אתה יוצר קשר לפני שאתה מניח את הטלפון. מרחק לא נמדד רק בקילומטרים.')],[
o('regular','Agree a regular call with Dad','לקבוע שיחה קבועה עם אבא','dad','I will answer. Do not start by asking if I saw the goal.','אני אענה. אל תפתח בזה שתשאל אם ראיתי את השער.',[flag('life:dad:contact','regular'),bond('dad',3)]),
o('visit','Agree a future visit without promising a ticket','לסכם ביקור עתידי בלי להבטיח כרטיס','dad','When we know the date and the cost, we make a plan.','כשנדע תאריך ועלות נעשה תוכנית.',[flag('life:dad:contact','visit')]),
o('photo','Send a photograph and a proper letter','לשלוח תמונה ומכתב אמיתי','dad','I put it on the fridge. The magnet is stronger than your handwriting.','שמתי על המקרר. המגנט חזק יותר מכתב היד שלך.',[flag('life:dad:contact','letter')])])]),
]

ADULTHOOD[0]!.scenes[0]!.callbacks=[{when:is('life:home:trust','hidden'),lines:[s('friend','If you call home, this time tell them where we really are.','אם אתה מתקשר הביתה, הפעם תגיד איפה אנחנו באמת.')]}]
ADULTHOOD[1]!.scenes[2]!.callbacks=[{when:is('life:promise:shift','broken'),lines:[s('friend','Your colleague called. You should answer him before talking about the game.','העמית שלך התקשר. כדאי שתענה לו לפני שמדברים על המשחק.')]}]
ADULTHOOD[5]!.scenes[2]!.callbacks=[{when:is('life:home:place','abroad'),lines:[s(null,'The familiar kitchen is on the screen today, not outside your door.','המטבח המוכר נמצא היום במסך, לא מעבר לדלת שלך.')]}]
ADULTHOOD[1]!.scenes[1]!.options.find(o=>o.id==='work')!.action=[s(null,'You complete the hours, return the tools and collect only the agreed wage.','אתה משלים את השעות, מחזיר כלים ומקבל רק את השכר שסוכם.')]
ADULTHOOD[1]!.scenes[1]!.options.find(o=>o.id==='renegotiate')!.action=[s(null,'You call before the shift, agree the change, and work the shorter paid task.','אתה מתקשר לפני המשמרת, מסכם את השינוי ומבצע את העבודה הקצרה שבתשלום.')]
ADULTHOOD[1]!.scenes[1]!.options.find(o=>o.id==='miss')!.action=[s(null,'You do not work the shift. No wage is collected. Your colleague’s call remains to answer.','אתה לא מבצע את המשמרת. לא מתקבל שכר. השיחה מהעמית מחכה לתשובה.')]
