import {chapter, scene, s, o} from './write'
import {flag, is, bond} from './types'

export const LATER = [
chapter('c7a-meeting',35,3,['The folding table','השולחן המתקפל'],['A supporters’ project needs hands, not another speech. Three people bring three different problems.','פרויקט אוהדים צריך ידיים, לא עוד נאום. שלושה אנשים מביאים שלוש בעיות שונות.'],'meeting-page',['A page with crossed-out promises','דף עם הבטחות מחוקות'],['The crossed-out line was replaced with something we could do.','השורה שנמחקה הוחלפה במשהו שיכולנו לבצע.'],[
scene('S37','workshop','elder',['What is missing?','מה חסר?'],[s('elder','People, records, or materials. Choose one thing you can finish.','אנשים, מסמכים או חומרים. תבחר דבר אחד שאתה יכול לסיים.'),s('mate','The table itself could also use a volunteer.','גם השולחן עצמו ישמח למתנדב.')],['Take responsibility for one task','לקחת אחריות על משימה אחת'],[s(null,'You write your name beside one task and ask who must agree before it starts.','אתה רושם שם ליד משימה אחת ושואל מי צריך להסכים לפני שמתחילים.')],[
o('people','Organise volunteers and ask permission','לארגן מתנדבים ולבקש הסכמה','elder','Names, times, consent. A crowd is not a rota.','שמות, שעות, הסכמה. קהל הוא לא סידור עבודה.',[flag('life:project:role','people')]),
o('archive','Organise records and their sources','לסדר מסמכים ואת המקורות שלהם','elder','Keep the source with the claim. Leave the date blank if we cannot verify it.','תשמור את המקור ליד הטענה. תשאיר תאריך ריק אם אי אפשר לאמת אותו.',[flag('life:project:role','archive')]),
o('materials','List materials and a realistic budget','לרשום חומרים ותקציב מציאותי','mate','Measure before ordering. Especially when you are spending somebody else’s money.','תמדוד לפני שמזמינים. במיוחד כשהכסף של מישהו אחר.',[flag('life:project:role','materials')])]),
scene('S38','workshop','mate',['The tempting shortcut','קיצור הדרך המפתה'],[s('mate','We could put a convincing number on this and call it finished.','אפשר לכתוב פה מספר משכנע ולהגיד שסיימנו.'),s('elder','Convincing and verified are different words.','משכנע ומאומת הן מילים שונות.')],['Check the record before closing it','לבדוק את הרשומה לפני שסוגרים'],[s(null,'You compare the list, the evidence and the actual resources. The gap becomes visible.','אתה משווה את הרשימה, האסמכתאות והמשאבים שיש באמת. הפער נעשה גלוי.')],[
o('check','Verify the missing detail','לאמת את הפרט החסר','elder','This one has evidence. The other one stays pending.','לזה יש אסמכתא. השני נשאר בהמתנה.',[flag('life:project:method','verified')]),
o('reduce','Reduce the scope to what can be done','להקטין את ההיקף למה שאפשר לבצע','mate','A smaller thing completed. I can work with that.','דבר קטן יותר שהושלם. עם זה אני יכול לעבוד.',[flag('life:project:method','scoped')]),
o('pending','Mark the gap honestly and ask for help','לסמן את החסר בכנות ולבקש עזרה','elder','Now the next person knows what to look for.','עכשיו האדם הבא יודע מה לחפש.',[flag('life:project:method','pending')])],'count'),
scene('S39','room','friend',['A promise with an owner','הבטחה עם אחראי'],[s('friend','Did the meeting produce work or only more meetings?','הפגישה יצרה עבודה או רק עוד פגישות?')],['Deliver the small completed part','למסור את החלק הקטן שהושלם'],[s(null,'You deliver the list with its limits attached. It is usable because somebody can understand it.','אתה מוסר את הרשימה יחד עם המגבלות שלה. אפשר להשתמש בה כי מישהו מסוגל להבין אותה.')],[
o('continue','Keep one regular task','להמשיך במשימה קבועה אחת','friend','Then leave yourself time to remain a person too.','אז תשאיר לעצמך זמן להישאר גם בן אדם.',[flag('life:project:future','regular')]),
o('handover','Hand it over with clear instructions','להעביר הלאה עם הוראות ברורות','elder','I know where the evidence is. That is a proper handover.','אני יודע איפה האסמכתאות. זו העברה כמו שצריך.',[flag('life:project:future','handed')]),
o('pause','Finish this part and step back','לסיים את החלק הזה ולקחת צעד אחורה',null,'The task is done. You do not need to become the whole organisation.','המשימה הסתיימה. אתה לא צריך להפוך לכל הארגון.',[flag('life:project:future','paused')])])]),

chapter('c7b-same-table',37,3,['The same table','אותו שולחן'],['The old group meets again. Someone brings the same joke. Someone remembers the agreement you hoped they had forgotten.','החבורה נפגשת שוב. מישהו מביא אותה בדיחה. מישהו זוכר את הסיכום שקיווית ששכחו.'],'reunion-receipt',['A receipt nobody needs to keep','קבלה שכבר לא חייבים לשמור'],['Settling a debt is different from winning an argument.','לסגור חוב זה שונה מלנצח בוויכוח.'],[
scene('S40','room','friend',['What came back with you?','מה חזר איתך?'],[s('friend','Sit down. Tell us one thing that is not your team’s latest result.','שב. ספר דבר אחד שהוא לא התוצאה האחרונה של הקבוצה שלך.')],['Name the unfinished thing','לתת שם לדבר שלא הסתיים'],[s(null,'You put the old note on the table before anybody has to ask.','אתה מניח את הפתק הישן על השולחן לפני שמישהו צריך לבקש.')],[
o('ride','Admit the petrol debt from the last bus','להודות בחוב הדלק מהאוטובוס האחרון','friend','I remember the lift. I would rather have the friendship than interest.','אני זוכר את הטרמפ. אני מעדיף חברות על ריבית.',[flag('life:repair:target','ride')],is('life:promise:ride','open')),
o('shift','Admit the shift you still owe','להודות במשמרת שעדיין חייבים','mate','I am here. Talk to me, not about me.','אני פה. תדבר איתי, לא עליי.',[flag('life:repair:target','shift')],{any:[is('life:promise:shift','open'),is('life:promise:shift','broken')]}),
o('home','Admit the evening you did not keep','להודות בערב שלא קיימת','friend','We can repair something. We cannot go back and pretend you arrived.','אפשר לתקן משהו. אי אפשר לחזור ולהעמיד פנים שהגעת.',[flag('life:repair:target','home')],{any:[is('life:promise:home','open'),is('life:promise:home','broken')]}),
o('new','Make a small new agreement','לסכם הסכם קטן חדש','friend','A walk next week. No heroic promises.','הליכה בשבוע הבא. בלי הבטחות גבורה.',[flag('life:repair:target','new')])]),
scene('S41','street','friend',['The following week','בשבוע שאחרי'],[s(null,'The following week arrives. This is where an apology either becomes an action or stays a sentence.','השבוע הבא מגיע. כאן התנצלות הופכת למשהו שעושים או נשארת משפט.')],['Show up for the agreed repair','להגיע לתיקון שסוכם'],[s(null,'You arrive at the agreed place. The work is small enough to finish today.','אתה מגיע למקום שנקבע. העבודה קטנה מספיק כדי לסיים היום.')],[
o('ride','Do the errand that settles the ride','לבצע את הסידור שסוגר את הטרמפ','friend','Done. Keep the note if you like. You no longer owe the lift.','סיימנו. תשמור את הפתק אם תרצה. את הטרמפ אתה כבר לא חייב.',[flag('life:promise:ride','repaired'),flag('life:repair:done','ride'),bond('friend',4)],is('life:repair:target','ride')),
o('shift','Cover the agreed work and get paid','לכסות את העבודה שסוכמה ולקבל שכר','mate','This shift happened. That is what I needed.','המשמרת הזו התקיימה. זה מה שהייתי צריך.',[flag('life:promise:shift','repaired'),flag('life:repair:done','shift'),{e:'coins',by:24},bond('mate',4)],is('life:repair:target','shift')),
o('home','Keep the newly agreed evening','לקיים את הערב החדש שסוכם','friend','You put the phone away. Now you are here.','הנחת את הטלפון. עכשיו אתה פה.',[flag('life:promise:home','repaired'),flag('life:repair:done','home'),bond('friend',4)],is('life:repair:target','home')),
o('walk','Take the walk you agreed on','לצאת להליכה שסיכמתם','friend','A whole street without checking a score. We should put up a plaque.','רחוב שלם בלי לבדוק תוצאה. צריך לשים שלט.',[flag('life:repair:done','new')],is('life:repair:target','new')),
o('fail','Fail to keep this agreement too','לא לקיים גם את ההסכם הזה','friend','Then I stop planning around your promises for now.','אז כרגע אני מפסיק לתכנן לפי ההבטחות שלך.',[flag('life:repair:done','failed'),bond('friend',-3)])],'carry'),
scene('S42','kitchen','dad',['No grand speech','בלי נאום גדול'],[s('dad','You came back with a different face. What did you actually do?','חזרת עם פנים אחרות. מה עשית בפועל?')],['Put the receipt in the box','להניח את הקבלה בקופסה'],[s(null,'You write what happened, rather than what you meant to do.','אתה כותב מה קרה, ולא מה התכוונת לעשות.')],[
o('plain','Tell him plainly what happened','לספר לו בפשטות מה קרה','dad','That is a story I can understand. Even if it is unfinished.','זה סיפור שאני מבין. גם אם הוא עוד לא גמור.',[flag('life:repair:account','plain')]),
o('ask','Ask about one of his unfinished stories','לשאול על סיפור שלו שלא הסתיים','dad','There is one. Put the kettle on before I start.','יש אחד. תפעיל קומקום לפני שאני מתחיל.',[flag('life:repair:account','asked'),bond('dad',3)]),
o('private','Keep this account to yourself','לשמור את הסיפור הזה לעצמך',null,'The receipt stays honest even without an audience.','הקבלה נשארת כנה גם בלי קהל.',[flag('life:repair:account','private')])])]),

chapter('c8-seat',40,3,['A first time for somebody else','פעם ראשונה של מישהו אחר'],['Years have passed. Parenthood, if both chose it and it became their life, is now a daily reality. There is also a first visit without being a parent.','עברו שנים. הורות, אם שניהם בחרו בה והיא נעשתה חלק מחייהם, היא עכשיו יום־יום. יש גם ביקור ראשון בלי להיות הורה.'],'new-ticket',['A ticket with a different name','כרטיס עם שם אחר'],['An invitation is not an inheritance obligation.','הזמנה היא לא חובת ירושה.'],[
scene('S43','kitchen','dad',['Who is invited?','את מי מזמינים?'],[s('dad','Are you inviting somebody, or recruiting them? There is a difference.','אתה מזמין מישהו או מגייס אותו? יש הבדל.')],['Ask the new person what they want','לשאול את האדם החדש מה הוא רוצה'],[s(null,'You explain the noise, the walk and the option to leave. Then you listen to the answer.','אתה מסביר על הרעש, ההליכה והאפשרות לצאת. ואז מקשיב לתשובה.')],[
o('child','Bring your child, who wants to try','לבוא עם הילד שלך, שרוצה לנסות','child','Can we go outside if it is too loud?','אפשר לצאת החוצה אם יהיה רועש מדי?',[flag('life:family','child')],is('life:family:intent','parent')),
o('newfan','Invite a friend trying football for the first time','להזמין חבר שמנסה כדורגל בפעם הראשונה','friend','I want to try it. I reserve the right to ask silly questions.','אני רוצה לנסות. שומר לעצמי זכות לשאלות טיפשיות.',[flag('life:family','newfan')]),
o('none','Respect the refusal and go without a newcomer','לכבד סירוב וללכת בלי מצטרף חדש','dad','A no is an answer too. The seat can wait.','גם לא זו תשובה. הכיסא יכול לחכות.',[flag('life:family','none')])]),
scene('S44','tunnel','steward',['The right to stop','הזכות לעצור'],[s('steward','Nobody has to prove anything at this gate. Here is the way out if you need it.','אף אחד לא צריך להוכיח משהו בשער הזה. הנה הדרך החוצה אם צריך.')],['Check the exits and set the pace','לבדוק יציאות ולקבוע קצב'],[s(null,'You find the quieter edge of the walkway before entering.','אתה מוצא את הצד השקט יותר של המעבר לפני הכניסה.')],[
o('slow','Take the walk slowly','לעשות את הדרך לאט',null,'The first visit is allowed to take longer than yours.','לביקור הראשון מותר לקחת יותר זמן משלך.',[flag('life:newcomer:pace','slow')]),
o('explain','Explain one thing and let the rest be new','להסביר דבר אחד ולתת לשאר להיות חדש',null,'You name the pitch. The person beside you finds the sky without help.','אתה נותן שם לדשא. האדם שלצידך מוצא את השמיים בלי עזרה.',[flag('life:newcomer:pace','explain')]),
o('outside','Stay outside and decide whether to enter','להישאר בחוץ ולהחליט אם להיכנס',null,'A first visit may be a look from the gate. Nobody takes the ticket away.','ביקור ראשון יכול להיות מבט מהשער. אף אחד לא לוקח את הכרטיס.',[flag('life:newcomer:pace','outside')])]),
scene('S45','room','dad',['Who owns the memory?','של מי הזיכרון?'],[s('dad','Do not tell them what the best part was. Ask.','אל תגיד להם מה היה החלק הכי טוב. תשאל.')],['Save the answer, including a no','לשמור את התשובה, כולל לא'],[s(null,'You leave room on the ticket for another handwriting. Or leave it blank.','אתה משאיר מקום על הכרטיס לכתב יד אחר. או משאיר אותו ריק.')],[
o('ask','Ask what they would choose next time','לשאול מה ירצו בפעם הבאה',null,'The answer belongs to the invited person. It may include coming back, or not.','התשובה שייכת למי שהוזמן. היא יכולה לכלול לחזור או לא.',[flag('life:newcomer:agency','asked')]),
o('draw','Invite a drawing instead of a verdict','להציע ציור במקום פסק דין',null,'The drawing includes a huge sandwich. You cannot argue with the evidence.','בציור יש סנדוויץ׳ ענקי. אי אפשר להתווכח עם האסמכתא.',[flag('life:newcomer:agency','draw')]),
o('wait','Let the day settle without another question','לתת ליום לשקוע בלי עוד שאלה',null,'The ticket goes into the box without becoming a contract.','הכרטיס נכנס לקופסה בלי להפוך לחוזה.',[flag('life:newcomer:agency','wait')])])]),

chapter('c8a-plan',45,3,['This time, my pocket','הפעם, בכיס שלי'],['Once Dad held the tickets. This time they are in your pocket. Before a journey becomes a memory, it needs a date, money, and willing people.','פעם אבא החזיק את הכרטיסים. הפעם הם בכיס שלך. לפני שנסיעה הופכת לזיכרון צריך תאריך, כסף ואנשים שרוצים לבוא.'],'trip-plan',['A plan with margins','תוכנית עם שוליים'],['There was room to change our minds.','היה מקום לשנות את דעתנו.'],[
scene('S46','kitchen','dad',['Ask before buying','לשאול לפני שקונים'],[s('dad','You have a plan already? Tell me about the walking before you tell me about the seats.','כבר יש לך תוכנית? ספר על ההליכה לפני שאתה מספר על המושבים.')],['Agree who is coming','לסכם מי בא'],[s(null,'You ask each person separately. An invitation does not purchase their agreement.','אתה שואל כל אדם בנפרד. הזמנה אינה קונה את ההסכמה שלו.')],[
o('pair','Go with Dad; he agrees','לצאת עם אבא; הוא מסכים','dad','Yes. Just leave time to sit down before we arrive.','כן. רק תשאיר זמן לשבת לפני שנגיע.',[flag('life:trip:party','dad')]),
o('three','Invite Dad and the willing newcomer','להזמין את אבא ואת המצטרף שרוצה','dad','Three tickets, then. Ask them about the pace too.','אז שלושה כרטיסים. תשאל גם אותם על הקצב.',[flag('life:trip:party','three')],{any:[is('life:family','child'),is('life:family','newfan')]}),
o('solo','Respect Dad’s wish to stay home','לכבד את הרצון של אבא להישאר בבית','dad','Bring me a story afterwards. That is the trip I want this time.','תביא לי סיפור אחר כך. זו הנסיעה שאני רוצה הפעם.',[flag('life:trip:party','solo')])]),
scene('S47','bedroom','dad',['A real budget','תקציב אמיתי'],[s(null,'These are fictional game units, not a promise of real ticket prices. Check what you actually earned.','אלה יחידות כסף במשחק, לא הבטחה למחירי כרטיסים במציאות. בדוק מה הרווחת בפועל.')],['Count the money and book the feasible plan','לספור כסף ולסגור תוכנית שאפשר לממן'],[s(null,'You put the money beside the route. No option can spend money you do not have.','אתה מניח כסף ליד המסלול. אי אפשר לבחור תוכנית שמוציאה כסף שאין לך.')],[
o('far','Fund a longer trip with 40 game units','לממן נסיעה ארוכה ב־40 יחידות',null,'The longer route is paid for. This is not a claim about a historical away fixture.','המסלול הארוך מומן. זו אינה טענה על משחק חוץ היסטורי.',[{e:'coins',by:-40},flag('life:trip:budget','paid'),flag('life:trip:route','far')],{min:['coins',40]}),
o('local','Fund a local outing with 20 game units','לממן יציאה מקומית ב־20 יחידות','dad','Near is fine. I remember near very well.','קרוב זה טוב. אני זוכר קרוב היטב.',[{e:'coins',by:-20},flag('life:trip:budget','paid'),flag('life:trip:route','local')],{min:['coins',20]}),
o('shared','Choose a free walk by the ground and a home evening','לבחור הליכה חינמית ליד המגרש וערב בבית','dad','We still go together if I chose to come. You have not bought a worse memory.','אם בחרתי לבוא, עדיין הולכים יחד. לא קנית זיכרון פחות טוב.',[flag('life:trip:budget','free'),flag('life:trip:route','walk')])],'count'),
scene('S48','street','elder',['The route matters','גם הדרך חשובה'],[s('elder','The shortest route has steps. The slower one has a bench. Ask who needs what.','בדרך הקצרה יש מדרגות. באיטית יש ספסל. תשאל מי צריך מה.')],['Check the route and pack the bag','לבדוק את הדרך ולארוז'],[s(null,'You check the bag, the agreed pace and the backup plan.','אתה בודק את התיק, הקצב שסוכם ותוכנית הגיבוי.')],[
o('slow','Choose the slower route with breaks','לבחור דרך איטית עם הפסקות','dad','Good. Now I do not have to pretend your pace is mine.','טוב. עכשיו אני לא צריך להעמיד פנים שהקצב שלך הוא שלי.',[flag('life:trip:pace','slow'),flag('life:trip:prepared',true)]),
o('direct','Use the direct route, with a stop available','לבחור בדרך הישירה עם אפשרות לעצירה',null,'A stop remains part of the plan, even if it is not needed.','עצירה נשארת חלק מהתוכנית גם אם לא צריך אותה.',[flag('life:trip:pace','direct'),flag('life:trip:prepared',true)]),
o('home','Change the outing to a home evening before leaving','לשנות לערב בבית עוד לפני היציאה','dad','Then we know what we are doing. No dramatic surprise at a gate.','אז אנחנו יודעים מה עושים. בלי הפתעה דרמטית בשער.',[flag('life:trip:pace','home'),flag('life:trip:prepared',true)])],'carry')]),

chapter('c8b-your-turn',46,3,['Your turn','התור שלך'],['The bag is ready. You do not have to prove that your plan was perfect. You have to take care of the people who agreed to it.','התיק מוכן. אתה לא צריך להוכיח שהתוכנית מושלמת. אתה צריך לדאוג לאנשים שהסכימו לה.'],'return-ticket',['The ticket in my pocket','הכרטיס בכיס שלי'],['The person matters more than completing the route.','האדם חשוב יותר מהשלמת המסלול.'],[
scene('S49','room','dad',['At the door','ליד הדלת'],[s(null,'You check the plan one last time. If Dad stayed home, the conversation happens by phone.','אתה בודק את התוכנית פעם אחרונה. אם אבא נשאר בבית, השיחה מתקיימת בטלפון.'),s('dad','Where did you put the tickets?','איפה שמת את הכרטיסים?')],['Check the agreed plan before the day starts','לבדוק את הסיכום לפני שמתחיל היום'],[s(null,'You check the names, the bag and the chosen route.','אתה בודק שמות, תיק והמסלול שנבחר.')],[
o('carry','Carry what the others agreed you would carry','לסחוב את מה שסיכמתם שתסחב','dad','I used to carry the bag too. Apparently it has been gaining weight for forty years.','גם אני סחבתי פעם. כנראה התיק עולה במשקל כבר ארבעים שנה.',[flag('life:trip:care','carried')]),
o('share','Divide the bag fairly with consent','לחלק את התיק בהסכמה',null,'Nobody is handed a burden as a test of loyalty.','אף אחד לא מקבל משקל כמבחן נאמנות.',[flag('life:trip:care','shared')]),
o('light','Leave unnecessary things at home','להשאיר דברים מיותרים בבית','dad','Three scarves and a radio. Are we moving in?','שלושה צעיפים ורדיו. אנחנו עוברים לגור שם?',[flag('life:trip:care','light')])]),
scene('S50','bus-stop','elder',['The plan meets the day','התוכנית פוגשת את היום'],[s(null,'The plan meets an actual day. A seat, a pause or a closed entrance matters more than your confidence.','התוכנית פוגשת יום אמיתי. כיסא, הפסקה או כניסה סגורה חשובים יותר מהביטחון שלך.')],['Make the adjustment and act on it','לבצע את ההתאמה בפועל'],[s(null,'You stop before the next part. The people involved are asked, not informed after the decision.','אתה עוצר לפני החלק הבא. שואלים את האנשים שההחלטה נוגעת להם, לא מודיעים להם אחרי שהתקבלה.')],[
o('pause','Take the pause, then continue if everyone agrees','לעצור ואז להמשיך אם כולם מסכימים',null,'The pause becomes part of the day. Nobody calls it a defeat.','ההפסקה הופכת לחלק מהיום. אף אחד לא קורא לזה הפסד.',[flag('life:trip:adjustment','pause')],{not:'life:trip:at-home'}),
o('accessible','Use the checked alternative route','להשתמש בדרך החלופית שנבדקה',null,'You follow the marked route, not a shortcut invented on the spot.','אתה משתמש בדרך המסומנת, לא בקיצור דרך שהמצאת במקום.',[flag('life:trip:adjustment','alternative')],{not:'life:trip:at-home'}),
o('return','Choose to return or remain home together','לבחור לחזור או להישאר יחד בבית',null,'You change the destination and tell everyone. Care is an action too.','אתה משנה יעד ומעדכן את כולם. גם דאגה היא מעשה.',[flag('life:trip:adjustment','home')])]),
scene('S51','room','dad',['Afterwards','אחר כך'],[s('dad','So. Tell me what you noticed.','נו. ספר מה ראית.'),s(null,'The answer belongs to the route you actually completed. No fictional result is added to the archive.','התשובה שייכת למסלול שביצעת בפועל. לא מוסיפים תוצאה מומצאת לארכיון.')],['Finish the day, not an imagined match','לסיים את היום, לא משחק מדומיין'],[s(null,'The bag comes down. You write the destination that really happened.','התיק יורד מהכתף. אתה כותב את היעד שבאמת היה.')],[
o('attended','Remember the outing you completed','לזכור את היציאה שהשלמת','dad','You looked after the day. That is what I remember.','דאגת ליום הזה. זה מה שאני זוכר.',[flag('life:trip:result','outing')],{all:[{not:'life:trip:at-home'},{not:'life:trip:free'}, {any:[is('life:trip:adjustment','pause'),is('life:trip:adjustment','alternative')]}]}),
o('walk','Remember the walk and the home evening','לזכור את ההליכה ואת הערב בבית','dad','You do not need a turnstile to have a story.','לא צריך קרוסלה כדי שיהיה סיפור.',[flag('life:trip:result','walk')],{all:[{flag:'life:trip:free'},{not:'life:trip:at-home'},{not:'life:trip:returned'}]}),
o('home','Keep the home evening as its own ending','לשמור את הערב בבית כסיום בפני עצמו','dad','Then that was our day. Put it in the box as it was.','אז זה היה היום שלנו. תכניס לקופסה כמו שהוא.',[flag('life:trip:result','home')])])]),

chapter('finale',46,3,['The box stays open','הקופסה נשארת פתוחה'],['There are tickets here, and things that never passed through a turnstile. A scarf. A note. A name in someone else’s handwriting.','יש כאן כרטיסים ודברים שמעולם לא עברו בקרוסלה. צעיף. פתק. שם בכתב יד של מישהו אחר.'],'box-label',['A blank label','תווית ריקה'],['There is space for a life that is not ours.','יש מקום לחיים שאינם שלנו.'],[
scene('S52','bedroom','dad',['Which thing first?','מה מוציאים קודם?'],[s('dad','The oldest thing is not always the one you keep reaching for.','הדבר הכי ישן הוא לא תמיד הדבר שאליו היד הולכת.')],['Take one real keepsake out','להוציא מזכרת אחת אמיתית'],[s(null,'You take an object from the box, not a summary of your score.','אתה מוציא חפץ מהקופסה, לא סיכום של הניקוד שלך.')],[
o('scarf','Take the first scarf','להוציא את הצעיף הראשון','dad','You used to wear it like a blanket.','פעם לבשת אותו כמו שמיכה.',[flag('life:legacy:object','scarf')]),
o('debt','Take the note about an agreement','להוציא את הפתק על ההסכם',null,'Some lines are settled. Some remain honest reminders.','חלק מהשורות סגורות. אחרות נשארות תזכורת כנה.',[flag('life:legacy:object','agreement')]),
o('trip','Take the last day’s ticket or note','להוציא את הכרטיס או הפתק מהיום האחרון','dad','This time you held the plan.','הפעם אתה החזקת את התוכנית.',[flag('life:legacy:object','trip')])]),
scene('S53','room','friend',['The version you tell','הגרסה שאתה מספר'],[s('friend','You can tell a story without making yourself the hero of every scene.','אפשר לספר סיפור בלי להפוך את עצמך לגיבור בכל סצנה.')],['Tell one story with its actual outcome','לספר סיפור אחד עם התוצאה האמיתית שלו'],[s(null,'You say who helped, what went wrong, and what remained unfinished.','אתה מספר מי עזר, מה השתבש ומה נשאר לא גמור.')],[
o('thanks','Tell it as a thank-you','לספר אותו כתודה',null,'The names become the centre of the story.','השמות הופכים למרכז הסיפור.',[flag('life:legacy:voice','thanks')]),
o('funny','Tell the funny part, without erasing the cost','לספר את החלק המצחיק בלי למחוק את המחיר','friend','Keep the sandwich in the story. Leave me some dignity.','תשאיר את הסנדוויץ׳ בסיפור. תשאיר לי קצת כבוד.',[flag('life:legacy:voice','funny')]),
o('honest','Tell the unfinished part honestly','לספר בכנות את החלק שלא הסתיים',null,'Nobody awards a trophy. Somebody understands.','אף אחד לא מעניק גביע. מישהו מבין.',[flag('life:legacy:voice','honest')])]),
scene('S54','bedroom','dad',['Leave room','להשאיר מקום'],[s('dad','Do not fill the whole box. Whoever comes after you needs somewhere to put their own things.','אל תמלא את כל הקופסה. מי שיבוא אחריך צריך מקום לדברים שלו.')],['Choose how the box continues','לבחור איך הקופסה ממשיכה'],[s(null,'You put a blank label beside the keepsakes. The blank part is deliberate.','אתה מניח תווית ריקה ליד המזכרות. החלק הריק מכוון.')],[
o('give','Offer the box without requiring the same colours','להציע את הקופסה בלי לדרוש אותם צבעים',null,'They may take a story, a scarf, or nothing yet. The invitation remains theirs to answer.','אפשר לקחת סיפור, צעיף או בינתיים כלום. ההזמנה נשארת שלהם לענות עליה.',[flag('life:legacy','offered')],{any:[is('life:family','child'),is('life:family','newfan')]}),
o('open','Keep an open box for future visitors','לשמור קופסה פתוחה למי שיבוא',null,'There is room for somebody you have not met yet.','יש מקום למישהו שעוד לא פגשת.',[flag('life:legacy','open')]),
o('own','Keep your box and offer someone a new one','לשמור את שלך ולהציע למישהו קופסה חדשה',null,'Your life does not have to become somebody else’s instructions.','החיים שלך לא צריכים להפוך להוראות של מישהו אחר.',[flag('life:legacy','new-box')])])]),
]

LATER[1]!.scenes[0]!.callbacks=[
 {when:is('life:promise:ride','open'),lines:[s('friend','I still have the petrol note. No, I did not frame it. Yet.','הפתק על הדלק עדיין אצלי. לא, לא מסגרתי. עדיין.')]},
 {when:is('life:promise:shift','broken'),lines:[s('mate','There is an empty square on my shift board with your name in it.','יש משבצת ריקה בלוח המשמרות שלי עם השם שלך בתוכה.')]},
 {when:is('life:promise:home','broken'),lines:[s('friend','We have another evening to talk about before planning a new one.','יש לנו עוד ערב לדבר עליו לפני שמתכננים ערב חדש.')]},
]
 LATER[2]!.scenes[0]!.callbacks=[{when:is('life:family:intent','parent'),lines:[s(null,'This branch allows a later, mutual choice of parenthood after years of life. Considering it earlier did not commit you to it.','במסלול הזה אפשר לבחור בהמשך בהורות משותפת אחרי שנים של חיים. הרצון לשקול זאת בעבר לא מחייב אותך לבחור בכך.')]}]
LATER[4]!.scenes[0]!.callbacks=[
 {when:is('life:trip:party','solo'),lines:[s(null,'Dad chose to stay home. You check in by phone before your own outing.','אבא בחר להישאר בבית. אתה בודק איתו בטלפון לפני היציאה שלך.')]},
 {when:is('life:trip:party','three'),lines:[s(null,'The newcomer is invited too. Their pace is part of the plan.','גם המצטרף הוזמן. הקצב שלו הוא חלק מהתוכנית.')]},
]
 LATER[4]!.scenes[1]!.callbacks=[
 {when:is('life:trip:pace','home'),lines:[s(null,'Today’s route is a home evening. You put the kettle on instead of going to the station.','המסלול היום הוא ערב בבית. מפעילים קומקום במקום לצאת לתחנה.')]},
 {when:is('life:trip:pace','slow'),lines:[s('elder','The bench you checked is here. Use it before somebody has to ask.','הספסל שבדקת נמצא כאן. תשתמש בו לפני שמישהו יצטרך לבקש.')]},
]
LATER[4]!.scenes[2]!.callbacks=[
 {when:is('life:trip:party','solo'),lines:[s(null,'You tell Dad about your outing by phone. He was not at the ground with you.','אתה מספר לאבא בטלפון על היציאה שלך. הוא לא היה איתך במגרש.')]},
 {when:is('life:trip:adjustment','home'),lines:[s('dad','Coming home was the right decision for this day.','לחזור הביתה הייתה ההחלטה הנכונה ליום הזה.')]},
]
LATER[5]!.scenes[0]!.callbacks=[
 {when:is('life:trip:result','home'),lines:[s(null,'The final note records a home evening, not a journey you did not complete.','הפתק האחרון מתעד ערב בבית, לא נסיעה שלא השלמת.')]},
 {when:is('life:shirt:origin','earned'),lines:[s('dad','That shirt? You worked for it. I remember you counting twice.','החולצה הזו? עבדת בשבילה. אני זוכר שסָפרת פעמיים.')]},
 {when:is('life:shirt:origin','handed'),lines:[s('dad','The old shirt still has the repair by the sleeve.','בחולצה הישנה עדיין יש את התיקון ליד השרוול.')]},
]

// Routing facts are committed with the physical planning step, never with its dialogue alone.
for(const choice of LATER[3]!.scenes[1]!.options) choice.effects!.push(flag('life:trip:free',choice.id==='shared'))
for(const choice of LATER[3]!.scenes[2]!.options) choice.effects!.push(flag('life:trip:at-home',choice.id==='home'))
for(const choice of LATER[4]!.scenes[1]!.options) choice.effects!.push(flag('life:trip:returned',choice.id==='return'))
LATER[4]!.scenes[1]!.locations=[{room:'kitchen',when:{flag:'life:trip:at-home'}},{room:'bus-stop',when:{not:'life:trip:at-home'}}]
LATER[4]!.scenes[0]!.presence={none:[is('life:trip:party','solo')]}
LATER[4]!.scenes[2]!.presence={none:[is('life:trip:party','solo')]}
for(const [sceneIndex,optionId] of [[1,'explain'],[2,'ask'],[2,'draw']] as const){
 LATER[2]!.scenes[sceneIndex]!.options.find(o=>o.id===optionId)!.when={any:[is('life:family','child'),is('life:family','newfan')]}
}
LATER[0]!.scenes[2]!.options.push(o('paid','Complete agreed paid setup work','לבצע עבודת הקמה בתשלום שסוכם','mate','The shelves are installed. Here is the agreed pay, from the workshop, not the supporters’ budget.','המדפים הורכבו. זה השכר שסוכם, מהסדנה ולא מתקציב האוהדים.',[{e:'coins',by:24},flag('life:project:future','paid')],is('life:project:role','materials')))
LATER[0]!.scenes[2]!.options.find(o=>o.id==='paid')!.action=[s(null,'You complete the measured assembly before accepting the wage.','אתה מסיים את ההרכבה שנמדדה לפני שאתה מקבל שכר.')]
LATER[4]!.scenes[2]!.options.find(o=>o.id==='home')!.action=[s(null,'You spend the rest of the evening at home.','אתה מבלה את שאר הערב בבית.')]
LATER[1]!.scenes[1]!.action=[s(null,'The agreed day arrives. The next action will determine whether this repair happened.','היום שסוכם מגיע. הפעולה הבאה תקבע אם התיקון הזה בוצע.')]
for(const choice of LATER[1]!.scenes[1]!.options)choice.action=[s(null,choice.id==='fail'?'You do not arrive. Later you acknowledge the missed agreement.':'You show up and complete the specific task you agreed on.',choice.id==='fail'?'אתה לא מגיע. אחר כך אתה מכיר בכך שהחמצת את הסיכום.':'אתה מגיע ומשלים את המשימה המסוימת שסיכמת עליה.')]
LATER[2]!.scenes[1]!.company=[{who:'child',slot:'ahead',when:is('life:family','child')},{who:'friend',slot:'ahead',when:is('life:family','newfan')}]
LATER[4]!.scenes[0]!.company=[{who:'child',slot:'stool',when:{all:[is('life:trip:party','three'),is('life:family','child')]}},{who:'friend',slot:'stool',when:{all:[is('life:trip:party','three'),is('life:family','newfan')]}}]
LATER[4]!.scenes[2]!.company=LATER[4]!.scenes[0]!.company
