import Link from 'next/link'
import {Shell} from '@/components/master/Shell'
import {ClubCard} from '@/components/clubs/ClubCard'
import {readState} from '@/lib/master/store'
import {GATES} from '@/lib/master/types'
import {headers} from 'next/headers'
import {redirect} from 'next/navigation'
export const dynamic='force-dynamic'
export default async function Home(){const hc=headers().get('x-fan-life-club');if(hc)redirect(hc==='hapoel-tel-aviv'?'/ground':`/clubs/${hc}`);const {clubs}=await readState();return <Shell><main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">THE SUPPORTER UNIVERSE · VOL. 01</p><h1>ONE GAME.<br/>A THOUSAND<br/><em>LIFETIMES.</em></h1><p className="lede">The first shirt. The away bus. The goal you still talk about. Your club is more than a score. Step into its world.</p><Link className="button" href="#clubs">Find your club <span>↗</span></Link><p className="hero-index">13 GATES TO EXPLORE / ONE LIFE TO LIVE</p></div><div className="hero-art" role="img" aria-label="The original football ground illustration"><span>FROM THE TERRACES<br/>TO EVERYTHING ELSE.</span><div className="ticket"><small>ADMIT ONE</small><strong>SUPPORTER<br/>FOR LIFE</strong><p>NO EXPIRY DATE. NO AWAY DAYS OFF.</p><i/></div><small className="art-foot">THE WORKER ENGINE / FAN LIFE WORLDS</small></div></section><div className="ticker">THE SHIRT <i>✦</i> THE CITY <i>✦</i> THE PEOPLE <i>✦</i> THE MEMORIES <i>✦</i> THE LIFE</div><section className="section" id="clubs"><div className="section-head"><div><p className="eyebrow">01 / CHOOSE YOUR SIDE</p><h2>Different colours.<br/>Same obsession.</h2></div><p>Each club has its own history, identity and home.</p></div><div className="club-grid">{clubs.filter(c=>c.status!=='paused').map((c,i)=><ClubCard club={c} index={i} key={c.id}/>)}</div></section><section className="life-feature"><div>LIFE<small>THE STORY MODE</small></div><article><p className="eyebrow">THE GAME BEYOND THE GAME</p><h2>You don’t just<br/>watch the story.<br/><em>You live it.</em></h2><p>Grow up with your club. Walk the streets, meet your people, make choices and carry the memories.</p><Link className="button light" href="/life">Start a Hapoel life ↗</Link></article></section><section className="section" id="gates"><div className="section-head"><div><p className="eyebrow">02 / PICK A GATE</p><h2>Thirteen ways in.</h2></div><p>The original Hapoel games, ready to explore.</p></div><div className="gates">{GATES.map(([n,name,url,desc])=><Link className="gate" href={url} key={n}><span>{String(n).padStart(2,'0')}</span><div><small>GATE {n}</small><h3>{name}</h3><p>{desc}</p></div><b>↗</b></Link>)}</div></section></main></Shell>}
