'use client'
// FAN LIFE fork of components/collector/GameShirtNote.tsx — generated by scripts/fanlife/fork-economy.py; edit the source or the script, not this file.

import { useEffect, useState } from 'react'

import { confirmOwned, gameItems } from '@/lib/collector/api'
import { t } from '@/lib/fanlife/i18n'

/**
 * A shirt assembled in a game sits in the closet with this note. It cannot be offered for sale or trade
 * (the table refuses) until its owner says they hold a real one — one tap, theirs to make.
 */
export function GameShirtNote({ itemId, onConfirmed }: { itemId: string; onConfirmed?: () => void }) {
  const [game, setGame] = useState(false)
  const [busy, setBusy] = useState(false)
  useEffect(() => {
    let live = true
    void gameItems().then((r) => { if (live && r.ok) setGame(r.items.includes(itemId)) })
    return () => { live = false }
  }, [itemId])
  if (!game) return null
  return (
    <div role="status" className="mb-3 border-s-plate border-ink bg-sheet py-2 pe-2 ps-3 font-body text-step--1 leading-relaxed text-ink">
      <p className="font-extrabold">{t('collector.game.title')}</p>
      <p className="text-muted">{t('collector.game.body')}</p>
      <button
        type="button"
        disabled={busy}
        onClick={() => {
          setBusy(true)
          void confirmOwned(itemId).then((r) => { setBusy(false); if (r.ok) { setGame(false); onConfirmed?.() } })
        }}
        className="mt-2 min-h-tap border-rule border-ink bg-paper px-3 font-body text-step--1 font-extrabold text-ink"
      >
        {t('collector.game.confirm')}
      </button>
    </div>
  )
}
