#!/usr/bin/env python3 -I
"""Writes docs/fanlife/43-kit-project-overview.md from the data (nothing typed by hand): per club, kits, seasons, images, SVGs, approval, gates."""
import glob,json,os
GATES=json.load(open('lib/master/launch-defaults.json'))
CL=[('aek-athens','AEK Athens','content/manual/kit-aek-athens.json'),('celtic','Celtic',None),('panathinaikos','Panathinaikos',None),('st-pauli','FC St. Pauli',None),('zrinjski-mostar','Zrinjski Mostar',None),('olympiacos','Olympiacos',None),('hapoel-petah-tikva','Hapoel Petah Tikva',None)]
L=['# Kit project — the whole picture','','_Generated by `scripts/kits/kit-coverage.py` from the data; do not edit by hand._','','| Club | Kits | Seasons | Catalogue images | SVG | Icons | Wave status | Gate 4 | Gate 5 |','|---|---|---|---|---|---|---|---|---|']
tk=0
for cid,name,f in CL:
    f=f or f'content/manual/kit-archive-{cid}.json';j=json.load(open(f));ks=j['kits'];ss=sorted({k['season'] for k in ks})
    d=f'public/club-kits/{cid}';n=lambda sub:len(glob.glob(f'{d}/{sub}/*'))
    st=set()
    for w in glob.glob(f'club-packs/{cid}/wave-kits-*.json'):
        for k in json.load(open(w)).get('kits',[]):st.add(k['status'])
    g=GATES.get(cid,[]);tk+=len(ks)
    L.append(f"| {name} | {len(ks)} | {ss[0]} → {ss[-1]} ({len(ss)}) | {n('cof')} | {n('svg')} | {n('icons')} | {', '.join(sorted(st)) or '—'} | {'open' if 4 in g else '—'} | {'open' if 5 in g else '—'} |")
hf=json.load(open('content/manual/kit-hfk-celtic.json'))['count']
L+=['',f'Total drawn kits across the archives: **{tk}**.',f'Celtic additionally carries **{hf}** historical drawings (1888–2023) from Historical Football Kits, shown as source images with their credit (non-commercial use, owner 10.10.2026).','','Hapoel Tel Aviv keeps its own archive (`public/kits/`, photographed kits) and is not part of the catalogue pipeline.','',
'## Where it lives','','- Static pages: `/kit-archive` (hub) and `/kit-archive/<club>`; in-app: `/clubs/<club>/kit-archive`.','- Files: `public/club-kits/<club>/{cof,svg,icons,crest.png}`; data: `content/manual/kit-archive-<club>.json`, `kit-cof-<club>.json`; waves: `club-packs/<club>/wave-kits-*.json`.','- Features: `kitViews()` feeds gates 4 and 5, the market, Rumble, the closet and the auction.','','## Approval','','AEK 99 (owner, "מאשר."), St. Pauli / Celtic / Panathinaikos / Zrinjski catalogue waves (owner, "מאשר הכל", 2026-10-09). Olympiacos catalogue wave (71 drawings, 13 flagged for a second reading) waits in review.','','## Known gaps (stated, not filled)','','- AEK: makers/sponsors before 2002 and 2012–2016 are not documented by either source.','- Olympiacos crest is the catalogue\'s 100px logo — football-logos.cc answered 403 and was not circumvented.','- Transcriptions marked `readUnsure` are the by-eye reads that deserve a second look.']
open('docs/fanlife/43-kit-project-overview.md','w').write('\n'.join(L)+'\n');print('\n'.join(L[:14]))
