'use client'
import Link from 'next/link'
import {useEffect,useState,useTransition} from 'react'
import type {ClubPlayer} from '@/lib/clubs/contract'
import type {MysteryView} from '@/lib/clubs/mystery'
import {startMystery,moveMystery} from '@/app/clubs/[slug]/[gate]/mystery-actions'
import {searchClubPlayers} from '@/lib/clubs/xi'
import {gameCopy} from '@/lib/clubs/game-copy'
import {recordActivity} from '@/lib/clubs/activity'
import type {UiLocale} from '@/lib/clubs/locale'
export function MysteryBoard({players,club,version,locale,contentLocale}:{players:ClubPlayer[];club:string;version:string;locale:UiLocale;contentLocale:string}){
 const copy=gameCopy(locale),[run,setRun]=useState<MysteryView|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(false),[pending,start]=useTransition(),[seconds,setSeconds]=useState(0)
 useEffect(()=>{if(!run||run.status!=='playing')return;const began=performance.now(),base=Math.max(0,run.serverNow-run.startedAt);setSeconds(base/1000);const timer=setInterval(()=>setSeconds((base+performance.now()-began)/1000),250);return ()=>clearInterval(timer)},[run])
 useEffect(()=>{if(run?.status==='solved')recordActivity(club,'blind-cow',`blind-cow:${version}:${run.rid}`,0)},[run,club,version])
 function act(move?:'reveal'|'guess'|'give_up',value:string|number=0,next=false){start(async()=>{try{const result=move&&run?await moveMystery(club,version,run.rid,move,value):await startMystery(club,version,next);if(result){setRun(result);setError(false);setQuery('')}else setError(true)}catch{setError(true)}})}
 const options=searchClubPlayers(players,query).slice(0,60)
 return <section className="game-panel" data-testid="mystery-board"><p>{copy.mysterySub}</p>{error&&<p role="alert">{copy.unavailable}</p>}{!run?<button className="game-button min-h-tap" disabled={pending} onClick={()=>act()}>{copy.mysteryStart}</button>:<><div className="game-hud"><span>{copy.clues}: {run.shown}/{run.total}</span><span>{copy.wrongGuesses}: {run.wrong}</span><span>{copy.seconds}: {seconds.toFixed(1)}</span></div><ol>{run.clues.map(c=><li className="game-panel" data-clue-n={c.n} key={c.n} lang={contentLocale} dir="auto"><small>{c.label}</small><p>{c.value}</p></li>)}</ol>{run.status==='playing'?<><div className="flex flex-wrap gap-4"><button className="game-button min-h-tap" disabled={pending||run.shown>=run.total} onClick={()=>act('reveal',run.shown)}>{copy.nextClue}</button><button className="game-button min-h-tap" disabled={pending} onClick={()=>act('give_up')}>{copy.giveUp}</button></div><label>{copy.search}<input className="min-h-tap w-full" type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="xi-player-list" data-testid="mystery-players">{options.map(p=><button className="game-button min-h-tap" key={p.id} data-player-id={p.id} disabled={pending||run.tried.includes(p.id)} onClick={()=>act('guess',p.id)}><bdi lang={contentLocale}>{p.name}</bdi>{run.tried.includes(p.id)&&` · ${copy.wrong}`}</button>)}</div></>:run.result&&<div data-testid="mystery-result" role="status"><h2>{run.status==='solved'?copy.correct:copy.gaveUp}</h2><h3 lang={contentLocale} dir="auto">{run.result.name}</h3><p>{copy.weightedTime}: {(run.result.weightedTimeMs/1000).toFixed(1)} · {copy.rawTime}: {(run.result.rawElapsedMs/1000).toFixed(1)}</p><p>{copy.mysteryScoring}</p>{run.result.sources.map(s=><p key={s.id}>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{copy.source}: <bdi>{s.title}</bdi> ↗</a>:<span>{copy.source}: <bdi>{s.title}</bdi></span>}</p>)}<Link className="game-button" href={`/clubs/${club}/archive?q=${encodeURIComponent(run.result.name)}&lang=${locale}`}>{copy['gate.archive']} ↗</Link><button className="game-button min-h-tap" disabled={pending} onClick={()=>act(undefined,0,true)}>{copy.replay}</button></div>}</>}</section>
}
