'use client'
import {useEffect,useMemo,useState} from 'react'
import type {ClubPlayer} from '@/lib/clubs/contract'
import {FORMATIONS} from '@/lib/game/formations'
import {fitOf} from '@/lib/xi/roles'
import {emptyXI,validateXI,searchClubPlayers} from '@/lib/clubs/xi'
import {xiKey,recordActivity} from '@/lib/clubs/activity'
import {gameCopy} from '@/lib/clubs/game-copy'
import type {UiLocale} from '@/lib/clubs/locale'
export function XIBuilder({players,club,locale,contentLocale}:{players:ClubPlayer[];club:string;locale:UiLocale;contentLocale:string}){
 const copy=gameCopy(locale),[xi,setXI]=useState(emptyXI),[slot,setSlot]=useState('GK'),[query,setQuery]=useState(''),[position,setPosition]=useState(''),[era,setEra]=useState(''),[fitOnly,setFitOnly]=useState(false),[limit,setLimit]=useState(40),[notice,setNotice]=useState('')
 useEffect(()=>{try{const raw=localStorage.getItem(xiKey(club));if(raw&&raw.length<20000){const next=validateXI(JSON.parse(raw),players);setXI(next);setSlot(FORMATIONS[next.formation]!.slots[0]!.slotId)}}catch{/* Invalid or unavailable device saves are not used. */}},[club,players])
 const formation=FORMATIONS[xi.formation]!,active=formation.slots.find(s=>s.slotId===slot)!,byId=useMemo(()=>new Map(players.map(p=>[p.id,p])),[players]),complete=Object.keys(xi.picks).length===11
 const eligible=useMemo(()=>searchClubPlayers(players,query).filter(p=>(!position||p.positions.includes(position as ClubPlayer['positions'][number]))&&(!era||p.fromYear!==null&&p.toYear!==null&&p.fromYear<=Number(era)+9&&p.toYear>=Number(era))&&(!fitOnly||fitOf(p.positions,active.role)!=='other')),[players,query,position,era,fitOnly,active.role])
 const decades=[...new Set(players.flatMap(p=>p.fromYear===null||p.toYear===null?[]:Array.from({length:Math.floor(p.toYear/10)-Math.floor(p.fromYear/10)+1},(_,i)=>(Math.floor(p.fromYear!/10)+i)*10)))].sort((a,b)=>a-b)
 function choose(player:ClubPlayer){if(Object.values(xi.picks).includes(player.id)&&xi.picks[slot]!==player.id){setNotice(copy.duplicate);return}setXI(p=>({...p,picks:{...p.picks,[slot]:player.id},captain:p.captain===p.picks[slot]?null:p.captain}));setNotice('');const empty=formation.slots.find(s=>s.slotId!==slot&&!xi.picks[s.slotId]);if(empty)setSlot(empty.slotId)}
 function save(){if(!complete)return;try{localStorage.setItem(xiKey(club),JSON.stringify(xi));recordActivity(club,'xi','xi');setNotice(copy.saved)}catch{setNotice(copy.savedUnavailable)}}
 return <section className="game-panel" data-testid="xi-builder"><p>{copy.xiSub}</p>
  <label className="game-filter">{copy.formation}<select value={xi.formation} onChange={e=>{setXI({formation:e.target.value,picks:{},captain:null});setSlot(FORMATIONS[e.target.value]!.slots[0]!.slotId);setNotice('')}}>{Object.keys(FORMATIONS).map(f=><option key={f}>{f}</option>)}</select></label>
  <p>{copy.slot} · {Object.keys(xi.picks).length}/11</p><div className="xi-pitch" data-testid="xi-pitch">{formation.slots.map(s=><button className="xi-slot min-h-tap" aria-pressed={slot===s.slotId} aria-label={`${s.slotId} ${byId.get(xi.picks[s.slotId]||'')?.name||s.role}`} key={s.slotId} style={{left:`${s.x}%`,bottom:`${100-s.y}%`}} onClick={()=>{setSlot(s.slotId);setNotice('')}}><small>{s.role}</small><span lang={contentLocale} dir="auto">{byId.get(xi.picks[s.slotId]||'')?.name||'+'}</span></button>)}</div>
  <div className="game-hud"><label>{copy.captain}<select value={xi.captain||''} onChange={e=>setXI(p=>({...p,captain:e.target.value||null}))}><option value="">—</option>{Object.values(xi.picks).map(id=><option key={id} value={id}>{byId.get(id)?.name}</option>)}</select></label><button className="game-button min-h-tap" onClick={()=>{setXI(p=>{const picks={...p.picks},id=picks[slot];delete picks[slot];return {...p,picks,captain:p.captain===id?null:p.captain}});setNotice('')}}>{copy.clear}</button></div>
  <div className="game-filters"><label>{copy.search}<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}}/></label><label>{copy.position}<select value={position} onChange={e=>{setPosition(e.target.value);setLimit(40)}}><option value="">{copy.all}</option>{(['GK','DF','MF','FW'] as const).map(p=><option key={p} value={p}>{copy[p]}</option>)}</select></label><label>{copy.years}<select value={era} onChange={e=>{setEra(e.target.value);setLimit(40)}}><option value="">{copy.anyEra}</option>{decades.map(d=><option key={d}>{d}</option>)}</select></label><label><input type="checkbox" checked={fitOnly} onChange={e=>{setFitOnly(e.target.checked);setLimit(40)}}/>{copy.fitOnly}</label></div>
  <h3>{copy.pick} · {active.role} · {eligible.length}</h3><div className="game-options" data-testid="xi-players">{eligible.slice(0,limit).map(p=>{const fit=fitOf(p.positions,active.role);return <button className="game-option min-h-tap" key={p.id} data-player-id={p.id} onClick={()=>choose(p)}><span lang={contentLocale} dir="auto">{p.name}</span><small>{p.positions.join(' / ')||copy.unknown} · {p.fromYear??'?'}–{p.toYear??'?'} · {fit==='fit'?copy.fit:fit==='other'?copy.fitOther:copy.fitUnknown}</small></button>})}</div>{eligible.length>limit&&<button className="game-button min-h-tap" onClick={()=>setLimit(n=>n+40)}>{copy.more}</button>}
  {complete&&<h3 data-testid="xi-complete">{copy.xiComplete}</h3>}<button className="game-button min-h-tap" disabled={!complete} onClick={save}>{copy.save}</button><button className="game-button min-h-tap" onClick={()=>{setXI(emptyXI());setSlot('GK');setNotice('')}}>{copy.reset}</button>{notice&&<p role="status">{notice}</p>}<p>{copy.localOnly}</p>
 </section>
}
