import type { EndingCard } from './chapter1986'
import type { Say } from './script'

/**
 * 1990 — the second movement of one childhood, and the first the boy walks into on his
 * own legs. Stage B, part one: Saturday, 12 May 1990, the last round of the second
 * division, and a father and a twelve-year-old at a kitchen table doing arithmetic.
 *
 * The rule from `chapter1986.ts` holds harder here, because this chapter is ABOUT
 * information: no line in this file states a score, a scorer, a minute or the parallel
 * result. What the radio says is generated by the match director from the anchor and
 * from rumour state the log records as rumour; what people at the table say is
 * arithmetic about a race the archive describes in words. Kobi says "how many do we
 * need"; nobody in this file answers with a number the archive does not hold.
 */

/**
 * ארבע שנים — the objects in the room, each one a year.
 *
 * Not a montage. The player looks at things, and the room changes around him while he
 * does: the poster peels, the school bag gets bigger, the cassettes arrive. Each entry is
 * what he sees, then what has changed when he looks up. The order is the player's; the
 * room ends the same way whichever object he looks at last.
 */
export type PassageObject = {
  id: string
  labelHe: string
  /** what he sees */
  lookHe: string
  /** what is different when he looks up */
  afterHe: string
}

export const PASSAGE_1990: PassageObject[] = [
  {
    /**
     * הקופסה האדומה — the one object in this room that came out of the last chapter.
     *
     * The four things the boy looked at used to be four pieces of dressing: a clipping, a
     * notebook, a scarf, a photograph. None of them was anything the player had earned,
     * which made the bridge a mood rather than a memory — and the bridge is the mechanism
     * this game built for exactly the opposite job.
     *
     * So the first of them is now the tin box, because every one of 1986's three endings
     * closes on the same sentence: you put it in the red box, THE FIRST THING IN IT. That
     * sentence is guaranteed — the chapter cannot end without one of those three cards —
     * so this line is true of every save that can reach this room, which is what lets it
     * be said at all. `PassageObject` carries no `Condition` and `PassageScene` evaluates
     * none, so anything written here is shown to everybody; the scrap of cloth and the
     * 1983 stub are both OPTIONAL, and naming either one here would be the game telling a
     * player about an afternoon he did not have. They are echoed where a branch can read
     * them instead (`d-box` and `d-go` in `chapter2000double.ts`).
     *
     * It does nothing. He does not take it out. It is still there, and the room says so.
     */
    id: 'clipping',
    labelHe: 'הקופסה האדומה',
    lookHe: 'קופסת פח מתחת למיטה. הדבר הראשון שנכנס אליה עוד למעלה, ומעליו כבר יש שכבה. אתה לא מוציא אותו. אתה רק בודק שהוא שם.',
    afterHe: 'הפוסטר מעל המיטה החליף ידיים. הכדור בפינה נעלם. מישהו גדל שתי מידות של נעליים.',
  },
  {
    id: 'notebook',
    labelHe: 'המחברת',
    lookHe: 'מחברת חשבון. בעמוד האחרון אין חשבון — יש הרכב, עם חצים, ומספר חולצה ליד כל שם.',
    afterHe: 'התיק של בית הספר גדל. יש בו ספרים שלא היו. ועל השולחן — קלטת.',
  },
  {
    id: 'scarf',
    labelHe: 'הצעיף',
    lookHe: 'הצעיף תלוי על המסמר ליד הדלת, ולא על הכיסא. מישהו החליט שיש לו מקום.',
    afterHe: 'הקיר ליד הדלת מלא: כרטיסים, פתק, תמונה של שלושה ילדים על קיר. אתה באמצע.',
  },
  {
    id: 'photo',
    labelHe: 'התמונה',
    lookHe: 'אבא, אמא, ואתה. אבא צעיר יותר ממה שאתה זוכר אותו. אמא לא מסתכלת למצלמה.',
    afterHe: 'ברדיו מהמטבח, מישהו מסובב את הכפתור. מדברים על שבת. מדברים על מספרים.',
  },
]

/** The card that ends the passage, and the only thing on screen for a moment. */
export const PASSAGE_CARD_HE = 'מאי 1990'

/** The first thing said in 1990, at the kitchen table, before the player has control. */
export const TABLE_1990: Say[] = [
  { who: null, text: 'שולחן המטבח. עיתון, עיפרון, קפה, וטרנזיסטור עם אנטנה מכופפת.' },
  { who: 'קובי', text: 'נו, כמה צריך?', closeUp: 'cuKobiTable' },
  { who: 'פוגי', text: 'רגע.' },
  { who: 'קובי', text: 'מה רגע?' },
  { who: 'פוגי', text: 'אני מחשב.' },
  { who: 'קובי', text: 'אתה בן שתים עשרה.' },
  { who: 'פוגי', text: 'בגלל זה אני מחשב יותר מהר ממך.' },
  { who: 'רחל', text: 'שניכם תאחרו.' },
]

/**
 * מי מדבר ב-1990 — the plates. The boy is older, so his plate is; his father is the
 * same man with the same face. Everybody on the terrace who is "a supporter" gets the
 * supporter plate, and the kids get the kid.
 */
export const PORTRAIT_1990: Record<string, string> = {
  'מישל': 'faceMichel',
  'אסף': 'faceAsaf',
  'פוגי': 'faceHero80',
  'קובי': 'faceKobi',
  'רחל': 'faceRachel90',
  'אופיר': 'faceOfir',
  'עמית': 'faceAmit',
  'רפי מהקיוסק': 'faceOldMan',
  'אוהד': 'faceSupporter',
  // בארי, older — the same Gate 7 fixture from 1986 (Stage A Director's Cut §43).
  'בארי': 'faceBarry',
  'אוהד עם רדיו': 'faceSupporter',
  'אוהד שיודע': 'faceSupporterB',
  'סדרן': 'faceUsher',
  'הקופאי': 'faceVendor',
  'מוכר': 'faceVendor',
  'ילד': 'faceKid',
  // שני הקבועים של אלנבי — שני השחקנים האלה מתויגים `era: '*'` ב-`scenes.ts`, כלומר הם
  // עומדים שם בכל פרק, ולכן כל מפה צריכה את הפלייטים שלהם.
  'המוכר': 'faceVendor',
  'הגבר': 'faceSupporterB',
}

export const OBJECTIVES_1990 = {
  howMany: 'שבת, 12 במאי. כמה צריך?',
  leaving: 'אבא מחכה. יוצאים.',
  leftWithout: 'אבא כבר בדרך. ללכת אחרי האדומים.',
  gate7: 'שער 7. שם עומדים.',
  halfGate: 'מחצית. הסדרן פותח את השער.',
  heardIt: 'נגמר. שמעת מהרחוב. הביתה.',
  promoted: 'עלינו?',
  findKobi: 'למצוא את אבא.',
  walkHome: 'הביתה. ביחד.',
} as const

/**
 * The 1990 endings. Same three shapes as 1986 — got in, got in late, never got in — and
 * the walk home is the ending, not a results screen (brief §24).
 */
export const ENDINGS_1990: Record<string, EndingCard> = {
  home: {
    id: 'home',
    titleHe: 'הביתה, זה לצד זה',
    bodyHe:
      'הרעש נשאר מאחור. הלכתם ברגל, שניכם, לא הוא לפניך ולא אתה לפניו. הוא לא החזיק לך את היד בכביש. לא היה צריך.',
    memoryHe: 'אמא שאלה "נו?" ושניכם אמרתם "עלינו". היא אמרה "יופי. נעליים בחוץ." שמת משהו בקופסה האדומה, ליד הדבר מ-1986.',
    memoryItem: 'promotion-table',
    after: {
      fromArt: 'kobi90-paper',
      toArt: 'kobi90-lean',
      lineHe: 'הוא יקרא את עמוד הספורט עוד הרבה שבתות. מהיום, לפעמים, אתה תדע משהו לפניו.',
    },
  },
  late: {
    id: 'late',
    titleHe: 'אחרי השריקה',
    bodyHe:
      'הגעת כשהדשא כבר היה מלא אנשים ולא שחקנים. לא ראית שער. ראית אלפי אנשים שלא הצליחו להפסיק לרוץ, ומצאת אותו ביניהם.',
    memoryHe: 'הרמת מהדשא פיסת נייר עם מספרים. מישהו חישב היום, ולא צדק, ולא היה אכפת לו. שמת את זה בקופסה.',
    memoryItem: 'folded-paper',
    after: {
      fromArt: 'kobi90-cheer',
      toArt: 'kobi90-stand',
      lineHe: 'הוא יעמוד בשער 7 עוד שנים. בשלב מסוים תעמוד שם בלעדיו, ותדע בדיוק איפה.',
    },
  },
  missed: {
    id: 'missed',
    titleHe: 'שמעת מהרחוב',
    bodyHe:
      'הרעש הגיע ממזרח בגלים, פעם אחר פעם, ואתה ספרת אותם ברחוב עם ילדים שלא ידעו לספור. ידעת לפני כולם. לא היית שם.',
    memoryHe: 'אבא חזר צרוד וחיבק את אמא במטבח. לא סיפר כלום. שמת בקופסה משהו שנשאר מהיום — יום שהיה, ולא היית בו.',
    memoryItem: 'newspaper',
    after: {
      fromArt: 'ofir90',
      // (24.9.2026) Ofir grown — `ofir90-smoke` was another man (`LEGACY_POSE`)
      toArt: 'ofir40-3q',
      lineHe: 'אופיר היה שם. הוא יספר לך על זה בבית הספר ביום ראשון, ולא ירחם.',
    },
  },
}

/** The morning after — school makes history small again (brief §25). */
export const SCHOOL_MORNING_1990: Say[] = [
  { who: null, text: 'יום ראשון, 13 במאי 1990. שבע בבוקר. אתה עייף כמו שלא היית אף פעם.' },
  { who: null, text: 'הצעיף בתוך התיק, מקופל מתחת לספר החשבון. חצי ממנו מציץ.' },
  { who: 'רחל', text: 'מה זה שם?' },
  { who: 'פוגי', text: 'כלום.' },
  { who: null, text: 'אתה דוחף אותו עמוק יותר, ויוצא לבוקר רגיל לגמרי.' },
  { who: 'אופיר', text: 'בא לאוסישקין השבוע?', closeUp: 'cuOfir90' },
]
