"""Fork The Worker's shirt economy into FAN LIFE (owner, 7.10.2026: "copy one to one, adapted to our hub").

The Worker keeps its Hebrew screens; FAN LIFE gets English copies of the same components, wired to
the same back end (the worker_* RPCs, PGlite in evaluation). Re-runnable: it regenerates every fork
from its source, so a fix made in The Worker can be carried over by running it again — edits that
belong only to FAN LIFE live in the files this script does NOT write (pages, catalogue, i18n).

  python3 scripts/fanlife/fork-economy.py            # write the forks
  python3 scripts/fanlife/fork-economy.py --check    # exit 1 if a fork is stale
"""
import os, re, sys

MAP = {}
def add(src, dst):
    MAP[os.path.normpath(src)] = os.path.normpath(dst)

for d, dst in [('components/market', 'components/fanlife/market'), ('components/auction', 'components/fanlife/auction'), ('components/collector', 'components/fanlife/collector')]:
    for f in sorted(os.listdir(d)):
        if f.endswith(('.ts', '.tsx')): add(f'{d}/{f}', f'{dst}/{f}')
for f in ['ClosetBoard.tsx', 'ClosetMetrics.tsx', 'ClosetScreen.tsx', 'ItemEditor.tsx', 'PrivacyPanel.tsx', 'api.ts']:
    add(f'app/kits/closet/{f}', f'components/fanlife/closet/{f}')
add('app/kits/closet/[handle]/PublicCloset.tsx', 'components/fanlife/closet/PublicCloset.tsx')
add('app/kits/market/MarketScreen.tsx', 'components/fanlife/screens/MarketScreen.tsx')
add('app/kits/market/item/[id]/ListingScreen.tsx', 'components/fanlife/screens/ListingScreen.tsx')
add('app/kits/market/c/[id]/ThreadScreen.tsx', 'components/fanlife/screens/ThreadScreen.tsx')
add('app/kits/auction/AuctionBoard.tsx', 'components/fanlife/screens/AuctionBoard.tsx')
add('app/kits/auction/[id]/LotRoom.tsx', 'components/fanlife/screens/LotRoom.tsx')
add('app/kits/auction/submit/[itemId]/SubmitLot.tsx', 'components/fanlife/screens/SubmitLot.tsx')
for f in ['AdminAudit.tsx', 'AdminConsole.tsx', 'AdminGate.tsx', 'AdminLots.tsx', 'AdminReports.tsx', 'AdminShops.tsx']:
    add(f'app/kits/admin/{f}', f'components/fanlife/admin/{f}')
for f in ['auction.ts', 'cards.ts', 'labels.ts', 'market.ts', 'notify.ts']:
    add(f'lib/collector/{f}', f'lib/fanlife/collector/{f}')

# FAN LIFE replacements for Worker pieces the economy reaches into (written by hand, not forked)
REPLACE = {
    'components/share/ShareRow.tsx': 'components/fanlife/ShareRow.tsx',
    'components/collector/ShirtThumb.tsx': 'components/fanlife/ShirtThumb.tsx',   # photos OR a drawn kit
    'components/auction/ShirtPicture.tsx': 'components/fanlife/ShirtPicture.tsx',
}
LINKS = [
    ('/kits/closet', '/closet'), ('/kits/market', '/market'), ('/kits/auction', '/auction'),
    ('/kits/archive', '/shirts'), ('/kits/admin', '/master/exchange'),
]

def resolve(spec, frm):
    if spec.startswith('@/'): base = spec[2:]
    elif spec.startswith('.'): base = os.path.normpath(os.path.join(os.path.dirname(frm), spec))
    else: return None
    for ext in ['', '.ts', '.tsx', '/index.ts', '/index.tsx']:
        if os.path.isfile(base + ext): return os.path.normpath(base + ext)
    return None

def alias(path):
    return '@/' + re.sub(r'\.(tsx?|json)$', '', path)

IMPORT = re.compile(r"""((?:import|export)[^'"]*?from\s*|import\(\s*)(['"])([^'"]+)\2""")

def fork(src):
    text = open(src, encoding='utf8').read()
    def swap(m):
        spec = m.group(3)
        if spec == '@/lib/i18n': return f"{m.group(1)}{m.group(2)}@/lib/fanlife/i18n{m.group(2)}"
        target = resolve(spec, src)
        if target is None: return m.group(0)
        if target in REPLACE: return f"{m.group(1)}{m.group(2)}{alias(REPLACE[target])}{m.group(2)}"
        if target in MAP: return f"{m.group(1)}{m.group(2)}{alias(MAP[target])}{m.group(2)}"
        if spec.startswith('.'): return f"{m.group(1)}{m.group(2)}{alias(target)}{m.group(2)}"
        return m.group(0)
    text = IMPORT.sub(swap, text)
    for a, b in LINKS:
        text = re.sub(re.escape(a) + r'(?=[/?"\'`$]|$)', b, text)
    text = text.replace('dir="rtl"', 'dir="ltr"').replace("'he-IL'", "'en-GB'").replace('"he-IL"', '"en-GB"')
    head = f"// FAN LIFE fork of {src} — generated by scripts/fanlife/fork-economy.py; edit the source or the script, not this file.\n"
    if text.startswith("'use client'") or text.startswith('"use client"'):
        first, rest = text.split('\n', 1)
        return first + '\n' + head + rest
    if text.startswith("import 'server-only'"):
        first, rest = text.split('\n', 1)
        return first + '\n' + head + rest
    return head + text

# FAN LIFE-only edits applied after the rewrite: (file, old, new). Each must match exactly once.
PATCHES = [
    ('components/fanlife/closet/ClosetBoard.tsx',
     '<ClosetMetrics items={items} shirts={shirts} archive={archive} shareRoute={sharePath} />',
     '<ClosetMetrics items={items} shirts={shirts} archive={archiveForCloset(archive, items, shirts)} shareRoute={sharePath} />'),
    ('components/fanlife/closet/ClosetBoard.tsx',
     "import { t, type MessageKey } from '@/lib/fanlife/i18n'",
     "import { t, type MessageKey } from '@/lib/fanlife/i18n'\nimport { archiveForCloset } from '@/lib/fanlife/scope'"),
    # a club without archive photographs: the drawn kit, as everywhere else in FAN LIFE
    ('components/fanlife/market/ShirtBits.tsx',
     "export function ArchivePhoto({ shirt, className = '', eager = false }: { shirt: CollectorShirt; className?: string; eager?: boolean }) {\n  return (",
     "export function ArchivePhoto({ shirt, className = '', eager = false }: { shirt: CollectorShirt; className?: string; eager?: boolean }) {\n  if (!shirt.src) return <ShirtThumb shirt={shirt} className={className} />\n  return ("),
    ('components/fanlife/market/ShirtBits.tsx',
     "import { Num } from '@/components/ui/Num'",
     "import { Num } from '@/components/ui/Num'\nimport { ShirtThumb } from '@/components/fanlife/ShirtThumb'"),
]

def patched(dst, text):
    for f, old, new in PATCHES:
        if f != dst: continue
        if text.count(old) != 1: raise SystemExit(f'patch did not match once in {dst}: {old[:60]}')
        text = text.replace(old, new)
    return text

check = '--check' in sys.argv
stale = []
for src, dst in MAP.items():
    out = patched(dst, fork(src))
    if check:
        if not os.path.isfile(dst) or open(dst, encoding='utf8').read() != out: stale.append(dst)
        continue
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, 'w', encoding='utf8').write(out)
if check:
    print('\n'.join(stale) or 'forks up to date'); sys.exit(1 if stale else 0)
print(len(MAP), 'files forked')
