"""Fork The Worker's shirt economy into FAN LIFE (owner, 7.10.2026: "copy one to one, adapted to our hub").

The Worker keeps its Hebrew screens; FAN LIFE gets English copies of the same components, wired to
the same back end (the worker_* RPCs, PGlite in evaluation). Re-runnable: it regenerates every fork
from its source, so a fix made in The Worker can be carried over by running it again — edits that
belong only to FAN LIFE live in the files this script does NOT write (pages, catalogue, i18n).

  python3 scripts/fanlife/fork-economy.py            # write the forks
  python3 scripts/fanlife/fork-economy.py --check    # exit 1 if a fork is stale
"""
import os, re, sys

MAP = {}
def add(src, dst):
    MAP[os.path.normpath(src)] = os.path.normpath(dst)

for d, dst in [('components/market', 'components/fanlife/market'), ('components/auction', 'components/fanlife/auction'), ('components/collector', 'components/fanlife/collector')]:
    for f in sorted(os.listdir(d)):
        if f.endswith(('.ts', '.tsx')): add(f'{d}/{f}', f'{dst}/{f}')
for f in ['ClosetBoard.tsx', 'ClosetMetrics.tsx', 'ClosetScreen.tsx', 'ItemEditor.tsx', 'PrivacyPanel.tsx', 'api.ts']:
    add(f'app/kits/closet/{f}', f'components/fanlife/closet/{f}')
add('app/kits/closet/[handle]/PublicCloset.tsx', 'components/fanlife/closet/PublicCloset.tsx')
add('app/kits/market/MarketScreen.tsx', 'components/fanlife/screens/MarketScreen.tsx')
add('app/kits/market/item/[id]/ListingScreen.tsx', 'components/fanlife/screens/ListingScreen.tsx')
add('app/kits/market/c/[id]/ThreadScreen.tsx', 'components/fanlife/screens/ThreadScreen.tsx')
add('app/kits/auction/AuctionBoard.tsx', 'components/fanlife/screens/AuctionBoard.tsx')
add('app/kits/auction/[id]/LotRoom.tsx', 'components/fanlife/screens/LotRoom.tsx')
add('app/kits/auction/submit/[itemId]/SubmitLot.tsx', 'components/fanlife/screens/SubmitLot.tsx')
for f in ['AdminAudit.tsx', 'AdminConsole.tsx', 'AdminGate.tsx', 'AdminLots.tsx', 'AdminReports.tsx', 'AdminShops.tsx']:
    add(f'app/kits/admin/{f}', f'components/fanlife/admin/{f}')
for f in ['auction.ts', 'cards.ts', 'labels.ts', 'market.ts', 'notify.ts']:
    add(f'lib/collector/{f}', f'lib/fanlife/collector/{f}')

# FAN LIFE replacements for Worker pieces the economy reaches into (written by hand, not forked)
REPLACE = {
    'components/share/ShareRow.tsx': 'components/fanlife/ShareRow.tsx',
    'components/collector/ShirtThumb.tsx': 'components/fanlife/ShirtThumb.tsx',   # photos OR a drawn kit
    'components/auction/ShirtPicture.tsx': 'components/fanlife/ShirtPicture.tsx',
}
LINKS = [
    ('/kits/closet', '/closet'), ('/kits/market', '/market'), ('/kits/auction', '/auction'),
    ('/kits/archive', '/shirts'), ('/kits/admin', '/master/exchange'),
]

def resolve(spec, frm):
    if spec.startswith('@/'): base = spec[2:]
    elif spec.startswith('.'): base = os.path.normpath(os.path.join(os.path.dirname(frm), spec))
    else: return None
    for ext in ['', '.ts', '.tsx', '/index.ts', '/index.tsx']:
        if os.path.isfile(base + ext): return os.path.normpath(base + ext)
    return None

def alias(path):
    return '@/' + re.sub(r'\.(tsx?|json)$', '', path)

IMPORT = re.compile(r"""((?:import|export)[^'"]*?from\s*|import\(\s*)(['"])([^'"]+)\2""")

def fork(src):
    text = open(src, encoding='utf8').read()
    def swap(m):
        spec = m.group(3)
        if spec == '@/lib/i18n': return f"{m.group(1)}{m.group(2)}@/lib/fanlife/i18n{m.group(2)}"
        target = resolve(spec, src)
        if target is None: return m.group(0)
        if target in REPLACE: return f"{m.group(1)}{m.group(2)}{alias(REPLACE[target])}{m.group(2)}"
        if target in MAP: return f"{m.group(1)}{m.group(2)}{alias(MAP[target])}{m.group(2)}"
        if spec.startswith('.'): return f"{m.group(1)}{m.group(2)}{alias(target)}{m.group(2)}"
        return m.group(0)
    text = IMPORT.sub(swap, text)
    for a, b in LINKS:
        text = re.sub(re.escape(a) + r'(?=[/?"\'`$]|$)', b, text)
    text = text.replace('dir="rtl"', 'dir="ltr"').replace("'he-IL'", "'en-GB'").replace('"he-IL"', '"en-GB"')
    head = f"// FAN LIFE fork of {src} — generated by scripts/fanlife/fork-economy.py; edit the source or the script, not this file.\n"
    if text.startswith("'use client'") or text.startswith('"use client"'):
        first, rest = text.split('\n', 1)
        return first + '\n' + head + rest
    if text.startswith("import 'server-only'"):
        first, rest = text.split('\n', 1)
        return first + '\n' + head + rest
    return head + text

# FAN LIFE-only edits applied after the rewrite: (file, old, new). Each must match exactly once.
PATCHES = [
    # the market redesign (9.10.2026): the thread wears the magazine's "The Conversation" — hooks for app/magazine.css (.fl-mk-*)
    ('components/fanlife/market/ThreadView.tsx',
     """    <div className="mt-stack">
      <Link
        href={item ? itemHref(item.id) : '/market'}
        className="inline-flex min-h-tap items-center font-body text-step--1 font-extrabold text-red underline underline-offset-4"
      >
        ← {item ? shirtName(shirt) : t('market.toMarket')}
      </Link>
""",
     """    <div className="fl-mk-thread">
      <Link href={item ? itemHref(item.id) : '/market'} className="fl-mk-back">
        <span aria-hidden="true">←</span> {item ? shirtName(shirt) : t('market.toMarket')}
      </Link>
      <h1 className="fl-mk-itemtitle">{handleLabel(other)}</h1>
"""),
    ('components/fanlife/market/ThreadView.tsx',
     '<aside className="flex flex-col gap-3 lg:sticky lg:top-4">',
     '<aside className="fl-mk-aside flex flex-col gap-3 lg:sticky lg:top-4">'),
    ('components/fanlife/market/ThreadView.tsx',
     """        className={`whitespace-pre-line break-words border-rule px-3 py-2 font-body text-step--1 leading-relaxed ${
          mine ? 'border-ink bg-ink text-paper' : 'border-ink bg-sheet text-ink'
        }`}""",
     """        className={`fl-mk-bubble whitespace-pre-line break-words font-body text-step--1 leading-relaxed ${mine ? 'fl-mk-bubble-mine' : ''}`}"""),
    ('components/fanlife/market/ThreadView.tsx',
     'className="flex items-end gap-2 border-rule border-ink bg-sheet p-2"',
     'className="fl-mk-composer"'),
    ('components/fanlife/market/ThreadView.tsx',
     """        className="min-h-tap shrink-0 border-rule border-ink bg-ink px-4 font-body text-step--1 font-extrabold text-paper disabled:opacity-50"
      >
        {t('market.compose.send')}""",
     """        className="fl-mk-send min-h-tap"
      >
        <span aria-hidden="true">➤</span>
        <span className="sr-only">{t('market.compose.send')}</span>"""),
    ('components/fanlife/closet/ClosetBoard.tsx',
     '<ClosetMetrics items={items} shirts={shirts} archive={archive} shareRoute={sharePath} />',
     '<ClosetMetrics items={items} shirts={shirts} archive={archiveForCloset(archive, items, shirts)} shareRoute={sharePath} />'),
    ('components/fanlife/closet/ClosetBoard.tsx',
     "import { t, type MessageKey } from '@/lib/fanlife/i18n'",
     "import { t, type MessageKey } from '@/lib/fanlife/i18n'\nimport { archiveForCloset } from '@/lib/fanlife/scope'"),
    # a guest's saved intents are cleared only for the shirts that were really saved; a failure stays for the next visit
    ('components/fanlife/closet/ClosetScreen.tsx',
     """        let saved = 0
        for (const intent of waiting) {
          const done = intent.action === 'have' ? await liveApi.have(intent.slug, intent.kitId) : await liveApi.wantSet(intent.slug, true, { kitId: intent.kitId })
          if (done.ok) saved += 1
        }
        clearIntents(waiting.map((intent) => intent.slug))""",
     """        let saved = 0
        const failed = new Set<string>()
        for (const intent of waiting) {
          const done = intent.action === 'have' ? await liveApi.have(intent.slug, intent.kitId) : await liveApi.wantSet(intent.slug, true, { kitId: intent.kitId })
          if (done.ok) saved += 1
          else failed.add(intent.slug)
        }
        clearIntents(waiting.map((intent) => intent.slug).filter((slug) => !failed.has(slug)))"""),
    # a club without archive photographs: the drawn kit, as everywhere else in FAN LIFE
    ('components/fanlife/market/ShirtBits.tsx',
     "export function ArchivePhoto({ shirt, className = '', eager = false }: { shirt: CollectorShirt; className?: string; eager?: boolean }) {\n  return (",
     "export function ArchivePhoto({ shirt, className = '', eager = false }: { shirt: CollectorShirt; className?: string; eager?: boolean }) {\n  if (!shirt.src) return <ShirtThumb shirt={shirt} className={className} />\n  return ("),
    ('components/fanlife/market/ShirtBits.tsx',
     "import { Num } from '@/components/ui/Num'",
     "import { Num } from '@/components/ui/Num'\nimport { ShirtThumb } from '@/components/fanlife/ShirtThumb'"),
]

# FAN LIFE prices in euros (owner, 7.10.2026: "the currency here is the euro, not the shekel").
# A row that already carries a currency keeps it — the tables are shared with The Worker, so a
# shekel price stays a shekel price; everything FAN LIFE creates or defaults to is EUR.
CURRENCY_SUBS = [
    (r"\?\? 'ILS'", "?? 'EUR'"), (r"Currency = 'ILS'", "Currency = 'EUR'"), (r"(\n\s*)currency: 'ILS',", r"\1currency: 'EUR',"),
    (r"null, 'ILS', ids", "null, 'EUR', ids"), (r"offer\.currency === 'ILS'", "offer.currency === 'EUR'"),
    (r"\bCURRENCIES\.map\(", "(['EUR'] as const).map("), (r">₪<", ">€<"),
    (r"useState<Draft>\(\(\) => draftOf\(item\)\)", "useState<Draft>(() => { const d = draftOf(item); return d.askingPrice === '' ? { ...d, currency: 'EUR' } : d })"),
    (r"(\n\s*)currency: item\.currency,(\n\s*hours:)", r"\1currency: 'EUR' as Currency,\2"),
]

def patched(dst, text):
    for a, b in CURRENCY_SUBS:
        text = re.sub(a, b, text)
    if len(re.findall(r'\bCURRENCIES\b', text)) == 1:   # only the import is left: drop it
        text = re.sub(r'\bCURRENCIES,\s*', '', text, count=1)
    for f, old, new in PATCHES:
        if f != dst: continue
        if text.count(old) != 1: raise SystemExit(f'patch did not match once in {dst}: {old[:60]}')
        text = text.replace(old, new)
    return text

# written by hand for FAN LIFE — never regenerated, never compared (the market redesign, 9.10.2026)
HAND = {os.path.normpath(p) for p in ['components/fanlife/market/ListingView.tsx']}

check = '--check' in sys.argv
stale = []
for src, dst in MAP.items():
    if dst in HAND: continue
    out = patched(dst, fork(src))
    if check:
        if not os.path.isfile(dst) or open(dst, encoding='utf8').read() != out: stale.append(dst)
        continue
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, 'w', encoding='utf8').write(out)
if check:
    print('\n'.join(stale) or 'forks up to date'); sys.exit(1 if stale else 0)
print(len(MAP), 'files forked')
