import Link from 'next/link'
import {Shell} from '@/components/master/Shell'
import {CORE_CLUB_IDS,REVIEW_CLUB_IDS,loadClub} from '@/lib/clubs/resolver'
import {SHARED_GATES,gateAvailability} from '@/lib/clubs/gates'
export const dynamic='force-dynamic'
export const metadata={title:'Club data · FAN LIFE'}
export default async function Page({searchParams}:{searchParams:{club?:string;page?:string}}) {
 const clubs=await Promise.all([...CORE_CLUB_IDS,...REVIEW_CLUB_IDS].map(loadClub)),selected=clubs.find(c=>c?.data.identity.id===searchParams.club)||clubs[0]!
 if(!selected)return null
 const {data,diagnostics}=selected,facts=data.archive.length?data.archive:data.timeline,rawPage=Number(searchParams.page)||1,page=Math.max(1,Math.min(Math.ceil(facts.length/100)||1,Math.floor(Number.isFinite(rawPage)?rawPage:1))),visible=facts.slice((page-1)*100,page*100)
 return <Shell><main id="main"><section className="section"><p className="eyebrow">SHARED GATES / DATA CONTRACT</p><h1>One engine. Different histories.</h1><p className="spaced">Games read eligible club data. Unknown fields stay unknown; imported research keeps its review status.</p>
 <div className="gates spaced">{clubs.map(c=>c&&<Link className="gate" key={c.data.identity.id} href={`?club=${c.data.identity.id}`}><div><h3>{c.data.identity.name}</h3><p>{c.data.readiness.state} · {c.data.timeline.length} eligible events</p></div><b>↗</b></Link>)}</div>
 <section className="panel spaced"><p className="eyebrow">{data.readiness.state}</p><h2>{data.identity.name}</h2><p>Version: <code>{data.version}</code></p><p>{data.timeline.length} eligible events / {data.readiness.target} for a full round</p><ul>{data.readiness.reasons.map(r=><li key={r}>{r}</li>)}</ul><Link className="button" href={`/clubs/${data.identity.id}/timeline`}>Open Timeline ↗</Link></section>
 <section className="panel spaced"><h2>Gate readiness and missing content</h2><p>Availability is computed from eligible compiled data. Admin pause and gate switches remain separate publishing controls.</p><div className="overflow-x-auto"><table className="w-full text-start"><thead><tr><th className="p-3 text-start">Gate</th><th className="p-3 text-start">Engine / state</th><th className="p-3 text-start">Eligible / full target</th><th className="p-3 text-start">What is needed</th></tr></thead><tbody>{SHARED_GATES.map(g=>{const r=gateAvailability(data,g.key),migrated=Object.hasOwn(data.gates,g.key);return <tr key={g.key} className="border-b-hair border-ink/20"><td className="p-3">{g.number}. {g.name}{r.playable&&<p><Link href={`/clubs/${data.identity.id}/${g.key}`}>Open ↗</Link></p>}</td><td className="p-3">{migrated?'Shared engine available':'Shared engine pending'}<br/>{r.state}</td><td className="p-3">{r.eligible}{r.target?` / ${r.target}`:' / not yet defined'}</td><td className="p-3">{g.requirement}{r.reasons.map(reason=><p key={reason}>{reason}</p>)}</td></tr>})}</tbody></table></div></section>
 <section className="panel spaced"><h2>Evidence and review</h2><p>Cross-source approval is recorded as automated, never as an owner decision. Existing Hapoel eligibility is carried forward from its curated archive.</p><div className="overflow-x-auto"><table className="w-full text-start"><thead><tr><th className="p-3 text-start">Event</th><th className="p-3 text-start">Status</th><th className="p-3 text-start">Evidence</th></tr></thead><tbody>{visible.map(f=><tr key={f.id} className="border-b-hair border-ink/20"><td className="p-3"><bdi>{'name' in f.value?f.value.name:f.value.title}</bdi><p className="text-sm">{f.value.on||'Exact date unknown'}</p></td><td className="p-3">{f.status} · {f.confidence}/3<br/>{f.approvedBy||'Not approved'}</td><td className="p-3">{f.sources.map(id=>{const s=data.sources.find(s=>s.id===id);return s?.url?<p key={id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a> · {s.access}</p>:<p key={id}>{s?.title||id}</p>})}<details><summary>Review note</summary><p>{f.notes}</p></details></td></tr>)}</tbody></table></div><nav className="spaced flex gap-4"><span>Page {page} of {Math.ceil(facts.length/100)||1}</span>{page>1&&<Link href={`?club=${data.identity.id}&page=${page-1}`}>Previous</Link>}{page*100<facts.length&&<Link href={`?club=${data.identity.id}&page=${page+1}`}>Next</Link>}</nav></section>
 {diagnostics.length>0&&<section className="panel spaced"><h2>Compiler diagnostics</h2><ul>{diagnostics.map((d,i)=><li key={`${d.record}:${i}`}><code>{d.record} / {d.code}</code>: {d.message}</li>)}</ul></section>}
 <p className="spaced">This console is read-only. Approval and rollback workflows belong to the later administration milestone.</p>
 </section></main></Shell>
}
